### ISSUE TITLE
Suppressing attachement is painfull (in fact, i can't do it through the windows app)

### ISSUE THREAD

**Issue by CapitainFlam** [keeweb/keeweb#1005]
Hi there, 

I tried several time to remove img attachement to some entries, through the MS WINDOWS STAND ALONE APP. I deleted really ten time my entiere entry, but never get to the point to supress only the attachment. 
To be honest, I did go through this pain thanks to the KeePass2Android app, where there is a "bin/trash button" in front of each attachment. Easy and simple. (...who said "you should copy that ?") 
I never understood the french "Cliquez sur le bouton de la pièce jointe en pressant la touche Maj ou ctrl-Supprimer pour enlever", that I would translate by "click on the attachment button while pressing MAJ, ou CTRL-SUPPR to remove". Honestly, if it's the real operation mode to do, i was never able to manage it. And if it's not, please improve the text to clarify what should be done ;-)

I added a MS WORD document to illustrate my bla bla.
[keeweb github.docx](https://github.com/keeweb/keeweb/files/2421683/keeweb.github.docx)

Thanks !

KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

**Comment by antelle** [comment]
From what I understood, it looks like it can be solved with better text, because the current one is far from ideal and confusing. Could you please suggest an improvement, so that I can update in on our translation system?

**Comment by Coises** [comment]
Even with better text, these cases would remain:

![keeweb-obscure-download-delete-1](https://user-images.githubusercontent.com/37453876/46238572-2755ea80-c342-11e8-9420-adb438f6bf0b.png)
![keeweb-obscure-download-delete-2](https://user-images.githubusercontent.com/37453876/46238573-27ee8100-c342-11e8-9953-28a291dedf74.png)


(The text is there... it’s just illegible because the attachment view overlaps it.)

No doubt we could fix that. I suggest, though, that the interface shouldn't require the user to view an attachment in order to delete it. Suppose a malformed attachment with a viewable extension causes KeeWeb to crash?

My thought is that user expectations would be:

1. Right-clicking the attachment button should give a menu of actions relevant to the attachment (download, remove, show in KeeWeb, open in system default program) rather than the same right-click menu that applies to the entry.

2. When displaying the attachment or its placeholder (for types that can’t be displayed in KeeWeb), actions for the attachment should be available as simple, clickable user interface elements. That might mean replacing the attachment buttons with action icons (download, remove, open in system default program, close) and requiring the user to close the view of one attachment before showing another, or just clipping the attachment view a bit higher so it doesn’t overlap wherever the actionable elements are shown. We could even keep the same text, but make `download` and `remove` clickable links—and make sure the attachment view can’t overlap it.

3. Dragging an attachment button to the trash can in the entry pane should remove the attachment (perhaps with a confirmation dialog). Dragging an attachment button out of KeeWeb to the desktop or to a file system folder should copy the attachment to that location.

**Comment by antelle** [comment]
@Coises I agree, what you describe as user expectations is the ideal behavior, however it would require some time to implement.

**Comment by Coises** [comment]
@CapitainFlam I think your question was never answered:

To remove an attachment, first click on the attachment’s button. Then (when you see the instructions you quoted) hold down the `Ctrl` key and press the `Delete` key. I think these are labeled `Ctrl` and `Suppr` on a French keyboard.

@antelle  Since you’re OK with that behavior, I’ll take a look at it. I can’t promise anything—there are parts of this code that are beyond my understanding at present—but if I can make some progress I’ll set up a pull request. I’m thinking a right-click menu on the attachment button—one of the things CaptainFlam tried—would be a good place to start.

**Comment by CapitainFlam** [comment]
@Coises, @antelle,

 After reading 4 times your answer, i FINALLY understood that i had to do a KEYBOARD COMBINATION, using CTRL, *and* DEL keystroke !  It was absolutly not obvious, because as I (wrongly) consider the keeweb app as a "browser in HTML encapsuled in an EXE file", it could not handle, or more precisely, it would not easily handle some shortcuts like CTRL+DEL keystroke. So i (wrongly) considered as NOT an option.
The text "click on the attachment button while pressing MAJ, ou CTRL-SUPPR to remove" was implying in my head that I HAD TO CLICK, with whatever combinaison on the keyboard. Not use ONLY a keyboard double stroke. 
So, easy solution, we should label the texte with something like "Option 1 : MAJ+click, option 2 : press both keyboard CTRL + DELETE", in order to clarify the idea that those two are separate. Generaly spealing, simply change the text with "something more clear" should not be too difficult ?

About the right click, there is *many* other aspect of the app that are managed through this right-click, so I think it's a good start to look at : 
"add a right click menu to A/ show in KeeWeb A'/ Show in default program B/ delete 1 attachement C/ delete ALL attachements (linked to the entry) D/ add an attachement"

Thanks for your answers, and the time you spent and will spend on this issue !

Capt'ain.
