### ISSUE TITLE
Fuzzy Search

### ISSUE THREAD

**Issue by omidkrad** [keeweb/keeweb#1022]
When I search `word1 word2 word3` it should not search the exact terms as in `"word1 word2 word3"` but should search `"word1" AND "word2" AND "word3"` because the search terms may not be next to each other in the entry. This is how the PC version of KeePass searches.

KeeWeb can make it even better by using some fuzzy search library such as [fusejs](http://fusejs.io/).

---------------------------------------------
KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

**Comment by omidkrad** [comment]
The issue that KeeWeb searches the whole phrase instead of using AND is really a bug that very much limits search of entries.

**Comment by btxtiger** [comment]
It would be already helpful to match `"Nextcloudserver Admin User Jason"` with `"nauj"`

**Comment by antelle** [comment]
The bot was misconfigured, sorry for a wrong notification.

**Comment by antelle** [comment]
v1.12 will have "Exact" checkbox. When it's unchecked (default behavior), search will be performed by separate words, as it's proposed here:
<img width="246" alt="Screen Shot 2019-09-30 at 20 32 26" src="https://user-images.githubusercontent.com/633557/65905764-773a1800-e3c1-11e9-8776-00821a4ab9e2.png">

**Comment by antelle** [comment]
Completed the feature and deployed it to [beta.keeweb.info](https://beta.keeweb.info), I'd be glad to hear from you if it matches your expectations.

**Comment by btxtiger** [comment]
Thanks for that.
I think the result could be improved by matching with this pattern, instead matching separated words:
The search key `naujason` should be convertet to regex `/^n.*a.*u.*p.*e.*t.*e.*r.*$/gmi`, so it can have anything in between the characters.
https://regex101.com/r/CPFnbP/1

**Comment by antelle** [comment]
Some time ago I have even written a small library for that: https://antelle.net/string-case-match/. Also other implementations exist od course.
I’m not sure if this should be implemented in KeeWeb though, because there are questions, for example, about having parts of search in different fields. Now, if you have an entry with title “hello world” and user “evil dude”, you can find it using “evil dude”. Should “ed” find it? “e d”? And “ev du”?
Another thing is highlighting the match: if you try it on my demo (a link in this comment), it’s clear *why* something is found because it’s highlighted, without it it would be strange.
Just to note, these questions are not really questions, but rather something I had in mind when thinking about fuzzy searching, so please don’t spend time answering them. I’m still researching and trying different options, if I come up with something usable and implementable, fuzzy search will be there too.

**Comment by noahfrederick** [comment]
> I’m still researching and trying different options

The gold standard for fuzzy matching is [FZF](https://github.com/junegunn/fzf). The [syntax](https://github.com/junegunn/fzf#search-syntax) is pretty elegant, I think.

**Comment by antelle** [comment]
The problem is, it solves another task: searching a list of files / strings is not the same as searching a list of entries with a list of individual fields inside.

**Comment by noahfrederick** [comment]
I realize the UI is going to be different, and that presents its own challenges, but actually, FZF *does* support searching lists with distinct fields. The man page goes into the details.

**Comment by omidkrad** [comment]
> Completed the feature and deployed it to [beta.keeweb.info](https://beta.keeweb.info), I'd be glad to hear from you if it matches your expectations.

The basic search that I needed is there that satisfies 99% of my use. Thanks for fixing it. I always have a "Keywords" field that helps me find entries easily, but I needed to be able to search them in random order. I use keywords for searching and tags for organization, but my search may be a combination of tags and keywords.

**Comment by antelle** [comment]
@omidkrad nice, glad to hear that! So for now I'll leave it like this and think about fuzzy search (not promising anything about it, it's somewhat complicated).

**Comment by omidkrad** [comment]
If it makes it easier, maybe we can fuzzy search only in the Notes field for now (with a checkbox for fuzzy search notes). But even without that I'm happy like it is. Thanks again! 👍
