### ISSUE TITLE
KeeWeb throws an error if it's already running: JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by antelle** [keeweb/keeweb#1079]
**Describe the bug**
Second instance of KeeWeb throws an error.

**To Reproduce**
1. Open KeeWeb
2. Run `/Applications/KeeWeb.app/Contents/MacOS/KeeWeb` again
3. The error appears

**Expected behavior**
Previous instance is activated

**Screenshots**
<img width="488" alt="screen shot 2019-01-06 at 19 05 14" src="https://user-images.githubusercontent.com/633557/50739856-037a2e80-11e6-11e9-9553-8c86a5ef9844.png">

**Environment**
KeeWeb v1.7.1 (22728d8, 2019-01-06)
Environment: electron v4.0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.7.1 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36

**Comment by Coises** [comment]
@antelle :

At least on Windows, while there is no error, the previous instance is not activated.

I don't yet have development/test set up for the new system, but I believe the answer lies here:

https://electronjs.org/docs/all#apprequestsingleinstancelock

The **makeSingleInstance** function called its argument as as a method of the _previous_ instance, not the current instance—which is why the first rewrite didn’t work. From the documentation, it looks like when Electron dumped **makeSingleInstance** and created **requestSingleInstanceLock**, they also created a new event, **second-instance**, to fire in the first instance when another instance attempts to acquire a lock. So something like:
```
    app.on('second-instance', restoreMainWindow);
```
inserted among the other `app.on` calls should work.

**Comment by antelle** [comment]
@Coises thanks! fixed in d9860935c1fcd710f00548c0e426f73f786f36c2, will be there in the next hotfix.
