### ISSUE TITLE
Option to hide password in generator

### ISSUE THREAD

**Issue by GrantMoyer** [keeweb/keeweb#1222]
It would handy to be able to hide the password in the generator. Not even knowing a password to a service is an extra layer of security.

The password generator dialog should have a toggle button which hides and shows the password, and the setting should persist across sessions.

Alternatives include closing your eyes while generating the password, or putting a "hide generated passwords" option somewhere in the settings. The first is impractical and I think the second hurts discoverability.

I have a PR ready to go if this is a desired feature; you can try it out on [my develop branch][devel]. My implementation looks like this:

[devel]: https://github.com/GrantMoyer/keeweb/tree/develop

|![Screen Shot 2019-08-05 at 19 23 33](https://user-images.githubusercontent.com/6333127/62501242-e5929d80-b7b7-11e9-9567-75275f4ca120.png) | ![Screen Shot 2019-08-05 at 19 24 18](https://user-images.githubusercontent.com/6333127/62501244-ea575180-b7b7-11e9-862e-0755df5629a7.png) |
|----|----|

**Comment by GrantMoyer** [comment]
Some more screen caps for completeness:

| ![Short password visible][short-vis] | ![Short password hidden][short-hid] |
|----|----|
| ![Long password visible][long-vis] | ![Long password hidden][long-hid] |


[short-vis]: https://user-images.githubusercontent.com/6333127/62501717-12e04b00-b7ba-11e9-9e46-86e52fb42283.png
[short-hid]: https://user-images.githubusercontent.com/6333127/62501779-4f13ab80-b7ba-11e9-9fb5-7d1751ac192d.png
[long-vis]: https://user-images.githubusercontent.com/6333127/62501782-53d85f80-b7ba-11e9-91f3-0da346377dca.png
[long-hid]: https://user-images.githubusercontent.com/6333127/62501786-55a22300-b7ba-11e9-8d4b-8f8b041f5317.png

**Comment by antelle** [comment]
Hi!

It makes sense, however the usage of this option seems to be somewhat limited, because the password is displayed anyway when you edit the password field. The only possible use case that I see is to paste the password and forget it forever, i.e. don't save it to the password manager, however it's strange. To complete the feature, we need to:

1. make it possible to show / hide passwords when editing
2. move the icon, it's not in the right place now (but that's much easier indeed)

**Comment by GrantMoyer** [comment]
The current behavior is:

* If you copy and paste the password into the password field you can see the password, since you are editing the field.
* If you use the pasword generator dialog on the field directly, by pressing the lighting bolt within the passwors field, the password is immediately hidden when you press okay.

I think it makes sense to always be able to see the password while editing, although I admit the method of keeping the password hidden isn't extremely intuitive. Where would be a preferable place to put the toggle button?

**Comment by antelle** [comment]
Yes, that's what I mean: in order to save the password to the password manager, you need to show it by editing a password field. The only possible use case is to generate a password and NOT to insert it to any of password fields, which is quite strange.

For example, if the password was hidden here during editing, it make a lot of sense to have it hidden there:

<img width="533" alt="image" src="https://user-images.githubusercontent.com/633557/62576050-57441780-b89c-11e9-8f29-188771846e88.png">

About the icon placing, let's not break the harmony of surrounding whitespace, I would add it somewhere here:

<img width="187" src="https://user-images.githubusercontent.com/633557/62576550-64add180-b89d-11e9-8aab-b7b7a658c105.png">

**Comment by antelle** [comment]
By the way, which browser shows this ugly white slider?

**Comment by GrantMoyer** [comment]
My browser is firefox with dark theme under wayland. The off center password text is because of the way I placed the new button.

In you're screen capture, pressing Ok would actually not reveal the password, since the password field is automatically deselected.

![Screen Capture](https://user-images.githubusercontent.com/633557/62576050-57441780-b89c-11e9-8f29-188771846e88.png?s=300)

**Comment by antelle** [comment]
> Note that in your screen capture, pressing Ok would actually not reveal the password, since the password field is automatically deselected.

Right, I forgot about it, thanks, because I was confused by "Copy" on the screenshot. In this case it makes sense to have this button, but only in that place, not in the one in the bottom, with the "Copy" button.

**Comment by antelle** [comment]
> My browser is firefox with dark theme under wayland.

Thanks, fixed that ugliness, it will be pretty after the next hotfix.
