### ISSUE TITLE
Notarize the macOS app

### ISSUE THREAD

**Issue by antelle** [keeweb/keeweb#1292]
macOS Catalina shows a warning for non-notarized apps:
<img width="532" alt="Screen Shot 2019-10-10 at 06 30 59" src="https://user-images.githubusercontent.com/633557/66539242-a706bf80-eb27-11e9-8b1b-707aca6685ff.png">

To get rid of it, we need to notarize the app.
Looks like an active Apple developer account is required now :trollface: 

https://medium.com/@TwitterArchiveEraser/notarize-electron-apps-7a5f988406db

**Comment by adaugherity** [comment]
I get this message with KeeWeb 1.11.9 on macOS 10.14.6.  Older KeeWeb downloads I have (1.7.2, 1.10.1) do not show this error.

Right-click, Open, then choosing Open in the dialog did work, and seems to have permanently dismissed it, as unmounting and reopening the .dmg does not bring up the dialog any more.

**Comment by antelle** [comment]
Mojave doesn't enforce notarization, so you can't see exactly the same dialog 😉 
There's, however, a similar one, and you most likely see it because since v1.11.8 Apple Developer ID was changed, most likely Apple warns you about this.

**Comment by adaugherity** [comment]
It's very similar, but the warning is for the disk image itself, not the app:
<img width="532" alt="Screen Shot 2019-10-15 at 1 46 43 PM" src="https://user-images.githubusercontent.com/1268533/66860162-3d851780-ef52-11e9-99f2-ff29412c3f51.png">
Right-click the .dmg, Open replaces the **OK** button with **Open** and **Cancel** buttons.

(I just downloaded 1.11.8 to test, since 1.11.9 seems to have been permanently approved once I did the right-click, Open, Open dance.  The 1.11.7 .dmg (and older) open without this dialog.  Perhaps if the app is notarized, you must notarize the .dmg too?)

**Comment by adaugherity** [comment]
Yes, 10.14.6 supplemental update 2 (18G103).

**Comment by antelle** [comment]
Looks like it's possible to notarize the DMG, yeah.

**Comment by Pupskuchen** [comment]
I just downloaded the DMG to install KeeWeb 1.11.10 on macOS Mojave (10.14.6 / 18G103) and got the same warning as @adaugherity posted.

**Comment by antelle** [comment]
Added another issue #1313

**Comment by antelle** [comment]
I don't know. I can't find anything about notarizing the DMG and I can't repeat the error.
For example, [here](https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/) and in some other places it's said that we can't do it.
Does anyone see this error on macOS Catalina?
