### ISSUE TITLE
Wrong filename when saving file in Safari 

### ISSUE THREAD

**Issue by cedhuf** [keeweb/keeweb#130]
Hi,
First, thanks for your work. I have a small issue though, with safari on OS X el capitain and keeweb v1.0.4. When saving a file (or a key), the downloaded filename is `unknown`. In chrome the file name is correct (`dbname.kdbx`).

Thanks.
Br,

**Comment by antelle** [comment]
It's known bug, because Safari doesn't implement neither [download file name setting](http://caniuse.com/#feat=download) for links, nor downloading binaries generated without server with proper file name. If you know a workaround, please let me know. I've added a [FAQ Q+A](https://github.com/antelle/keeweb/wiki/FAQ#sync) about it, and here's the [thread in file saving library we use](https://github.com/eligrey/FileSaver.js/issues/12).  
To help fixing it, [please tell Apple](https://bugs.webkit.org/show_bug.cgi?id=102914) that this is a good, necessary feature supported but all modern browsers but absent in safari.

**Comment by cedhuf** [comment]
Ok ! Thank you very much.

**Comment by antelle** [comment]
Update: Apple guys has started work on it.
https://bugs.webkit.org/show_bug.cgi?id=102914
https://webkit.org/status/#feature-download-attribute
So, we might have this working in the next Safari version.

**Comment by antelle** [comment]
Now we have special 'blocked' label for such issues. Reopening

**Comment by antelle** [comment]
New Safari just released but it still doesn't have link download attribute support 😢

**Comment by antelle** [comment]
Good news, it's working now on Safari TP.

**Comment by parameshjava** [comment]
@antelle will you please provide sample code snippet which is working for you to download file in Safari.

**Comment by antelle** [comment]
@parameshjava here's a minimalistic example: http://jsbin.com/kelijatigo/edit?html,js,output
Please note: safari TP, not released version.

**Comment by parameshjava** [comment]
@antelle Thanks a lot for your quick response.
