### ISSUE TITLE
Notarize the macOS DMG

### ISSUE THREAD

**Issue by antelle** [keeweb/keeweb#1313]
The same as #1292, but for the DMG

**Comment by antelle** [comment]
This doesn't seem to be required.

**Comment by Pupskuchen** [comment]
While [the article you linked in the other issue](https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/) says that the DMG doesn't need to be notarized, it also said you shouldn't sign it (because you'll have to notarize it if you do).
I'm not sure what the keeweb build is doing with the DMG, but could you make sure the DMG is not signed so you actually don't have to notarize it?

But I'm really just guessing here …

**Comment by antelle** [comment]
So, does the error happen on Catalina for anyone? First I need to repeat it, then I’ll be able to debug and fix it.

**Comment by antelle** [comment]
I've disabled code signing for DMG, but I can't validate if it works because for me it works with code signing as well, not sure why.
