### ISSUE TITLE
Alongside Electron version, also support Muon

### ISSUE THREAD

**Issue by DaniellMesquita** [keeweb/keeweb#1363]
I don't mean Brave browser's Muon, but the muon which is using Ultralight (tiny fork of Chromium), which is very simple and fast.
https://github.com/ImVexed/muon

**Comment by antelle** [comment]
There are very many missing features that are used in keeweb: WebAssembly, CSS user-select, JS Intl, selects, etc...

**Comment by DaniellMesquita** [comment]
selects?

**Comment by antelle** [comment]
Native select controls, I mean. They say, it crashes when you try to use it. There are actually more things listed there, I don’t think they’ll manage to implement all of them in the nearest future. 
Additionally, it’s not clear why we should switch at all, the difference between 150 (or even 200) and 40 mb file size doesn’t change anything now.

**Comment by DaniellMesquita** [comment]
File size only? Did you read their README.md?
It haves a lot difference in RAM usage.

**Comment by antelle** [comment]
Their statement about 200MB memory size in Electron is not true:

<img width="488" alt="Screen Shot 2019-12-04 at 18 11 22" src="https://user-images.githubusercontent.com/633557/70165268-e20a1700-16c2-11ea-970a-8a587575aa9f.png">

<img width="488" alt="Screen Shot 2019-12-04 at 18 26 32" src="https://user-images.githubusercontent.com/633557/70165705-a754ae80-16c3-11ea-95c0-a99a71ff57f5.png">

Unfortunately I can't run any example on muon, nor can I run it myself because they don't provide an executable and building it from sources is not what I would like to do to try if it works.

With this state of things I would assume memory there will grow once (if) they add more features.
