### ISSUE TITLE
[Feature request] One hand password

### ISSUE THREAD

**Issue by Rurik19** [keeweb/keeweb#142]
I found that to have password which I type with one hand is very convenient. Is it possible to add such option to password generator?

**Comment by antelle** [comment]
It's possible, as for now we support templates. Can you please give an example of such passwords, or maybe, even online generators, to have some references? I don't completely understand what does 1-hand password mean: like asdfqwerzxcv1234, consisting only of keys located on left/right keyboard side?

**Comment by Rurik19** [comment]
> like asdfqwerzxcv1234
Exactly!

**Comment by fuzzybear3965** [comment]
Please acknowledge that people (like me) may use different keyboard layouts. This should be coupled with a keyboard layout option.

**Comment by antelle** [comment]
> ability to change your default keyboard layout

Definitely we'll not support layout setting in keeweb settings. I'll check whether we can detect it. Most probably this api is not exposed...

**Comment by fuzzybear3965** [comment]
I'm reasonably confident that this isn't exposed at the application layer. Why will you "definitely not support" this? Too much work for too little reward?

**Comment by antelle** [comment]
> Too much work for too little reward?

Not only this (but this as well). First of all, we want to be a simple app, without [strange settings](http://www.usabilitycounts.com/wp-content/uploads/2012/01/simplicity.jpeg). 'One-hand' password is a feature that will be used by very low percentage of users, so there will be no special settings for it at all. There's also [a list of features we don't want to support](https://github.com/antelle/keeweb/wiki/Unsupported-Features) because of this reason.

**Comment by Rurik19** [comment]
I think that somethink like "user sets" of characters for generare passwords will solve this issue, with no dependency of keyboard layouts at all.

**Comment by antelle** [comment]
No: to much complex ui is required. Currently it will be implemented as a preset here: 
![keeweb 2016-04-13 08-14-17](https://cloud.githubusercontent.com/assets/633557/14483442/c057ac9e-014f-11e6-8c35-7085f46c3086.png)

**Comment by antelle** [comment]
We may have something like preset builder, when you enter range and get a password generated from it. Maybe even select some ranges and add characters. But this muse be exactly a preset, not custom range. Also this requires some UI for this.

**Comment by fuzzybear3965** [comment]
[That](http://www.usabilitycounts.com/wp-content/uploads/2012/01/simplicity.jpeg) was a cute graphic. I agree that one-hand password is a niche feature unlikely to be used by many users. But, KeeWeb will be used in contexts with strange character and length restrictions on passwords.

If I'm understanding your design/approach so far, you would like the user to be able to generate "presets" for different password requirements. These presets will allow the user to select whether certain pre-defined character sets are included/excluded for the generation of a particular password. What you do not want to include is the ability for users to generate their own custom sets of characters from which passwords will be derived.

If the above paragraph is correct, then I have a question. Why do you want to prohibit the user from generating passwords only from characters "A,!,b,c,z,<space>,*,q", for example? Why do you prefer to only allow the choice between pre-defined sets of characters, instead of also allowing for user-defined sets of characters?

**Comment by antelle** [comment]
No, that's not completely correct mostly because of terminology.
*Character sets* are literally sets of characters (on the picture above - ABC, 123, ...).
*Presets* are pre-selected character sets (on the picture - select control with 'default preset' in it).
I was against adding a character range, as @Rurik19 said above, so we'll not allow adding a custom item next to ABC, 123, ...
But it's ok to have more complex preset configuration UI, as this UI will be used for fine tuning of presets. So there we may allow to add custom ranges and exclusions and maybe patterns.

**Comment by fuzzybear3965** [comment]
Oh, I understand. Yeah, don't allow for the addition of more custom character sets (with checkboxes) in the UI. The ability to select, at will, the specific characters used to generate a password should make it in some version at a point in the future.

While this utility is less niche than a "one-hand" password, it is still reasonably niche, so it is fair to prioritize this fairly low.

**Comment by antelle** [comment]
Now you will be able to add a custom preset with any desired characters:
![left-hand-preset](https://cloud.githubusercontent.com/assets/633557/17650373/de860a7e-6254-11e6-84b1-a9495c1595d4.png)
And here we go:
![gen](https://cloud.githubusercontent.com/assets/633557/17650374/e8c4b92c-6254-11e6-834b-137bf1ca8992.png)

**Comment by Rurik19** [comment]
Thanks!
