### ISSUE TITLE
Does keeweb use file lock when opening a local disk kdbx

### ISSUE THREAD

**Issue by Sherlock-Holo** [keeweb/keeweb#1420]
When keeweb opens a local disk kdbx, does it use use file lock like flock to lock the kdbx file, ensure there is no another program modify the kdbx file.

I have a network filesystem and use it to share the kdbx file between my PC and server, if keeweb use flock to lock file, it may avoid data sync problem which will cause kdbx data incorrect when PC and server modifying the kdbx at the same time

**Comment by antelle** [comment]
Hi! In theory, the chance of an issue is very close to zero, because you need to modify the file exactly at the same time. This won't happen for our target audience (personal use), but can be a sort of issue for companies with large number of users opening the same file and saving it frequently.
Better to avoid it using atomic writes (locking doesn't work well cross-platform).

**Comment by Sherlock-Holo** [comment]
if keeweb read kdbx into memory, modify it, then write the whole file at a single `write` call, my network filesystem can promise the write call is atomic

**Comment by vladimiry** [comment]
>  Better to avoid it using atomic writes (locking doesn't work well cross-platform).

Atomic write solves the data format integrity issue. But a case when one user/process overrides changes made by another user/process will still remain. Introducing something like an `optimistic locking` / `counter` could be helpful until an automatic data merge gets implemented.

**Comment by antelle** [comment]
@vladimiry automatic merge has been here since the very first version of keeweb :) before saving a file its date is compared to what was loaded and if it's different, changes are merged. However there's indeed a possibility to modify the file in between, which should be nihil, that's why it's marked as future and most likely won't be fixed.

**Comment by antelle** [comment]
@Sherlock-Holo may I hear from you how the issue affects you, i.e. what's your setup?

**Comment by Sherlock-Holo** [comment]
I store the kdbx in my server, so I can read or modify the password from my PC and phone, sometimes need to use PC and phone at the same time, and modify some password, when PC and phone want to save password, if PC keeweb and phone save at the same time, it may cause data error. I have seem some times the kdbx data invalid and have to use the backup kdbx.

**Comment by antelle** [comment]
That's probably something else, I don't think you save them exactly at the same time. Do you have a chance to collect logs when it happens?

**Comment by Sherlock-Holo** [comment]
If it happened, I will try to send a log

**Comment by antelle** [comment]
If there's a log, please comment here, I'll reopen the issue
