### ISSUE TITLE
kwconfig.json security issue

### ISSUE THREAD

**Issue by thefiredragon** [keeweb/keeweb#1466]
There's a security issue,  
each person who has some knowledge can find on webconsole the the config file.
These config file contain the clear text password for the dropbox or webdav settings.
Is there a way to use a hash or make this config only readable for the main server?  
Think this would be critical.

The databases use password and key files, so thats not a problem but someone could grant access to the dropbox account or each other and when there are other files stored I think this could be a problem. 

Or delete just for fun all files from server.

**Comment by davidgiga1993** [comment]
There are multiple options:
1) Procted the webserver using basic auth or similar
2) Don't store the passwords

Using a hash makes no sense since it can't be recerved. 
Encrypting the password won't help either since the browser needs to know how to decrypt it (aka every user who can send requests to the server will also get those informations)

**Comment by thefiredragon** [comment]
Project Website With Password makes no Sense, 'cause website using ssl also webdav.
There's an issue Open Here that the service worker for pwa is broken.

Better would be a solution to store the password crypted in that config and the main application can decrypt it for usage. That should be possible. 

Double password check makes no sense when the databases use keyfiles.

**Comment by davidgiga1993** [comment]
Protecting the website makes the most sense.

Encrypting the password causes the same security issues you've mentioned since the app (which runs in the browser) needs to be able to decrypt the password. So anyone who can access the website will be able to decrypt the password as well.

**Comment by thefiredragon** [comment]
I understand you, 
I found also things like this https://www.vaultproject.io/
But I think to implement such features would be some work. 
But I think there are options to protect passwords which the application use. 
When the issue is solved that the pwa service worker will work with nginx auth that would be also okay. 
Would be bad to protect nginx with a password and the pwa will not work 'cause I need to delete the service worker.

**Comment by antelle** [comment]
That's not a security issue. If a web application needs to authenticate on a webdav server with a password, this password must be either available to it via config, or provided in runtime. 

If you choose to store the password in config, hashing won't help here, since we need to know the password. However if you're hosting your kdbx files on the same server as keeweb, you can put both keeweb and kdbx behind the same auth and you won't have to add a password, this way you can avoid having it in the config.

Asking password can be also another option, however it's not implemented, see #669.
