### ISSUE TITLE
Change Date format ..

### ISSUE THREAD

**Issue by homhom1416** [keeweb/keeweb#1606]
An option to Change Date format .. like 2020-09-22 OR 2020/09/22 Thir .. OR maybe called [ISO date Format ](https://en.wikipedia.org/wiki/ISO_8601)

**Comment by antelle** [comment]
Ideally it should also allow using system date/time formats.

**Comment by MrSnix** [comment]
**Hi, i'd like to work on that if possible.**

I was playing a bit with the codebase and it doesn't seems too complicate to implement.
I gave a shot and came up with this mockup.

![image](https://user-images.githubusercontent.com/20780192/100294882-687cd000-2f88-11eb-8ede-7a6b29c12059.png)

![image](https://user-images.githubusercontent.com/20780192/100294895-73376500-2f88-11eb-9a78-3476a337665d.png)

Right now i was wondering **how many options should we support**?
and if eventually we should add an external library like Moment.js to support multiple date-times formats or if we should work with what we currently have.

Right now i'm using an encoding like this one but maybe is not the best option.
```
 allDateTimeFormats: {
    'dd-mmm-yy hh:mm:ss': '26-NOV-20 18:01:31',
    'dd-mmm-yyyy hh:mm:ss': '26-NOV-2020 18:01:31',      
    'dd/mm/yy hh:mm:ss': '26/11/20 18:01:31',
    'dd/mm/yyyy hh:mm:ss': '26/11/2020 18:01:31',
    'dd-mm-yy hh:mm:ss': '26-11-20 18:01:31',
    'dd-mm-yyyy hh:mm:ss': '26-11-2020 18:01:31'
 }
```

We may use [Intl.DateTimeFormat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) if you want to avoid using 3td party libraries.
Sadly, seems like it doesn't allow to provide a pattern but some options to work with based upon the system locale.
I say "sadly" if we want allow a full customization (like allow the user to provide the pattern) otherwise i think it should be enough.

Let me know

**Comment by antelle** [comment]
Hi! Now when support of Intl is everywhere we should of course use it instead of the simple formatter, and this also means that we don’t need a possibility to change it, which can be done in system settings.
I assume, the need for it comes from date formats being displayed incorrectly now, so if we fix that, we won’t need this setting.

**Comment by antelle** [comment]
So, let’s not add any UI elements and instead fix how dates are presented.

**Comment by antelle** [comment]
So, regarding this issue, the new version will display proper formats depending on selected language. This is not quite correct and maybe we'll need more customization options, but let's see the reaction.
