### ISSUE TITLE
Error opening file Duplicate file id

### ISSUE THREAD

**Issue by softparade** [keeweb/keeweb#163]
Hi, i would like to open 2 keepass files simultaneously (which in fact are saved and shared from a same file), but keeweb (hosted 1.0.4) cannot and logs me this error :
`[open-view] Error opening file Duplicate file id`
Maybe it's a normal behaviour but I don't find how to change this file id manually
Thanks 

[Archive.zip](https://github.com/antelle/keeweb/files/175702/Archive.zip) pass: hello123

**Comment by antelle** [comment]
Opening such files simultaneously is not be supported for now. This may change in future.

**Comment by ShaunMaher** [comment]
@softparade I had this same issue.  I was able to work around it by using the original KeePass 2 application to export one of the files to XML, manually editing the XML to change the UUID of the root folder, creating a new file in KeePass and then importing the XML.

The "manually editing the XML" step might have actually been redundant because during the XML import you can tell KeePass to generate new IDs.

Take backups of your original files, etc. :)

**Comment by antelle** [comment]
> change the UUID of the root folder

This is not enough: all uuids must be changed. By changing only one uuid, you might have a lot of other bugs which may appear at very unusual places (moving, dragging, viewing, sorting, saving). Currently entries, groups and files are supposed to be unique.
Ok, let's fix it earlier..

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release

**Comment by antelle** [comment]
The issue will be closed automatically once changes are merged to master and the build deployed to production. let's keep it open until then..
