### ISSUE TITLE
Please make possible to deactivate some of system-wide shortcuts

### ISSUE THREAD

**Issue by bnsonear** [keeweb/keeweb#1733]
**Is your feature request related to a problem? Please describe.**
Some of system-wide shortcuts in KeeWeb sometimes conflicts with other program's shortcuts on Win10.
I tried to disable some of system-wide shortcuts but UI does not support to delete predefined shortcuts.

**Describe the solution you'd like**
Maybe adding a "Clear" item on mouse right-click menu (=context menu) at each shortcut field

**Describe alternatives you've considered**
Adding a check box beside the title of each system-wide shortcuts for activating or deactivating each shortcuts.

**Comment by antelle** [comment]
I just realized that there's already a possibility to do so, you can click the shortcut "button" and set it to some weird combination with all modifier keys that you will never type.

**Comment by antelle** [comment]
Looks like everything is done here.

**Comment by tgrelka** [comment]
I rely on many different shortcuts in different apps, some system-wide (e.g. Rectangle for MacOS, whose `Ctrl+Opt+W` to make a Window take up 2/3 of a screen conflicts with the defaul auto type of KeeWeb), which makes it rather annyoing to search for obscure combinations which I can set the shortcut to, especially given basically all my modifier layers are used for different kinds of things.

This really kind of sucks, because I don’t want to use KeeWeb with shortcuts much, or at least not as much as other apps, but it tends to react to actions I wanted to trigger in another app.

Setting the shortcut to an generally unused on is a *workaround*, but not a proper solution. Given how there are two system wide shortcuts which are unset by default (copy OTP and open KeeWeb), I’d wish for a button `x` for each shortcut to symply unset it.
