### ISSUE TITLE
New Autotype doesn't come to front anymore

### ISSUE THREAD

**Issue by dploeger** [keeweb/keeweb#1741]
**Describe the bug**
When hitting the Autotype shortcut, the autotype in 1.16.8 stays in the background.

**To Reproduce**
1. Open Keeweb and unlock a database
2. Select another app
3. Hit the autotype shortcut
4. The Keeweb window stays in the background

**Expected behavior**
The Keeweb windows jumps to front to show the autotype selections.

**Environment**
KeeWeb v1.16.8 (69f7b02, 2021-03-02)
Environment: electron v11.0.3
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.16.0 Chrome/87.0.4280.67 Electron/11.0.3 Safari/537.36

**Comment by antelle** [comment]
Hi! Let's check if v1.17.1 works.

**Comment by dploeger** [comment]
Oooohhh. It doesn't even update to 1.17. Then something broke with the update. I'll check this again.

**Comment by dploeger** [comment]
It was solved by removing ~/Library/Application Support/Keeweb

**Comment by dploeger** [comment]
I had this already with a previous major release. Only after removing the Application Data folder from Library, the app was fully rebuild.

Do you know if the new major updater might solve problems like this for 1.18?

**Comment by antelle** [comment]
Cool, so auto-type works, that's better!
Updater was reimplemented in v1.17 so that you won't have to manually download major versions anymore, I see that some people reported the same (v1.16 can't update to v1.17), and these issues with updater are expected to be solved in v1.17.x, yes. Meanwhile the updater may be more unstable now, but eventually we should get there.
