### ISSUE TITLE
Application crash with Yubikey

### ISSUE THREAD

**Issue by jivarson** [keeweb/keeweb#1743]
Keeweb 1.17.1 crashes when I insert or remove a YubiKey 5 in a USB-A-port.
It doesnt matter if the vaults are unlocked or not.

It doesn't crash when started while the yubikey is already inserted, hence it's still usable, but with a risk of dataloss if you have unsaved items..

Windows 20H2

**Comment by antelle** [comment]
Hi! In 1.17 native modules were moved to the main process, so crash in one of them crashes KeeWeb. To mitigate the issue, you can launch KeeWeb with --native-module-host-process argument.

I'll see what can be done, another process takes +50MB of memory so I'd prefer fixing the issue instead of keeping it in a separate process. Maybe switching to https://github.com/MadLittleMods/node-usb-detection instead of `node-usb` will solve it, I can create a build with it, would you mind checking if it works? I can't test it because VirtualBox with Windows inside also crashes when I remove a YubiKey.

**Comment by antelle** [comment]
Good news is that I managed to reproduce it. When VirtualBox doesn't crash, KeeWeb crashes if a YubiKey is inserted or removed. So I have a possibility to try different options and see what helps.

**Comment by antelle** [comment]
I made a new build, it seems to be working well for me, could you please check if it crashes?  
https://beta.keeweb.info/KeeWeb-win32-x64.zip

**Comment by jivarson** [comment]
> I made a new build, it seems to be working well for me, could you please check if it crashes?
> https://beta.keeweb.info/KeeWeb-win32-x64.zip

Works like a charm

**Comment by antelle** [comment]
Thank you very much! 🙏  I'll make a release with it soon

**Comment by antelle** [comment]
[v1.17.2](https://github.com/keeweb/keeweb/releases/tag/v1.17.2) is released and I hope it won't crash. Please give it a try and let me know if it solves your issue!
