### ISSUE TITLE
Add an option to clear long-lived token after app exit or short lifetime on access storage account

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#1753]
Now, the desktop KeeWeb caches online storage account's cookie and have the access to the storage account for a very long lifetime, e.g. Google Drive, and it saves the cookie file in the data folder, and I can keep accessing all the files after the first time that Google drive permission being granted. 

So, each time, after the app relaunch, KeeWeb can always have the access to the online storage account that previously logged in, which might be a concern to some users. And they might prefer to manually log into the drive account each time or use some sort of short-lived token for security purpose

Is it possible to add an option to clear the storage account's cookies file after the app exit, or any enhancement around the storage account access lifetime?

 It's kind of similar to incognito mode. For UX, I prefer to KeeWeb can cache the database shortcut (relative path of database in the online storage)  instead of re-selecting the storage type and the db file location after each login,  that's just my UX preference, but the only thing I would like to see is once the app got relaunch or the access got expired, KeeWeb can auto-trigger an OAuth request to ask user to login

**Comment by antelle** [comment]
Hi! I assume, by "cookie" here you mean refresh_ and access_tokens, because cookies don't give access to anything, they're just used by Google for analytics.

Now KeeWeb saves a long-lived refresh_token into storage that is used to get access to Google Drive later. Instead, in this so-called incognito mode, we can just use the access_token without saving anything to disk and require authentication when it expires. This will probably allow to achieve the desired level of security for what you described.

In terms of UX it will work exactly the same way as if click Log Out before closing the app, exactly as you described it.

**Comment by gynet** [comment]
yes, I was talking about the long-lived refresh token. Yes, your proposal seems good to me, the only thing might need to think about is the auto-sync method how to gracefully ask user to re-login when it is necessary

**Comment by antelle** [comment]
Auto-sync already does token refreshing when necessary and it can show the pop-up if required. In this sense it's already done, all we need, is make token storage optional and revoke them. Additionally it would be nice if in this mode of operation we don't get the refresh_token at all and request only access_token from storage providers.

**Comment by antelle** [comment]
Implemented, uploaded to [beta.keeweb.info](https://beta.keeweb.info).
