### ISSUE TITLE
Password Generator: Include each symbol group at least once

### ISSUE THREAD

**Issue by btxtiger** [keeweb/keeweb#1774]
**Is your feature request related to a problem? Please describe.**

1. It seems sometimes the generated password does not include each symbol group at least once, so I could have numbers activated, but the generated password does not include at least one number. This is really important in terms of password strength.

2. Suggestion: Some websites do not allow all special characters in passwords. So it might be an option to split up the special characters group into "safe special" and "extended special". Currently I'm using my own list of special characters using the "Additional symbols to include" input `!@#$%&*_+-=,.?;:` and not the "Special Symbols" group. 

**Describe the solution you'd like**
1. Checkbox to enable "Require each group"
2. Split "Special Symbols" into two separate groups

**Comment by antelle** [comment]
Hi!

1. I agree, if a checkbox is selected, the password must include all characters from each group at least once. The option is not needed, it's kind of expected.
2. Since it's easily achievable using generator patterns and the understanding of "safe special" is different on most of websites, we won't add this option to the generator.
