### ISSUE TITLE
Make the record fields fully editable

### ISSUE THREAD

**Issue by mkbaranovskyi** [keeweb/keeweb#1776]
**Is your feature request related to a problem? Please describe.**
I wanted to create a record for a credit card (Number, Expires, CVC/CVV, PIN, etc.) but there're unremovable clutter fields: User, Password and others. And the first two don't hide when I click `Hide empty fields` and they cannot be renamed to what I need. 
Another problem is that I can't edit new fields' names after their creation is finished. And I can't remove them, which is pretty annoying and requires to remove the whole record and re-create it if I typed a custom field name wrong or if I don't need it anymore.

**Describe the solution you'd like**
The ability to create, edit or remove any field at any time. Plus, the ability to re-arrange their order by dragging them would be nice.

_Off-topic: my Appimage stopped updating minor versions after the last major update to 1.17. And I can't even see the option anymore. Was that intended? Sorry for off-topic._

**Comment by antelle** [comment]
Hi! 👋 

All fields should be hidden when you select Hide empty fields, it works well for me:

<img width="521" alt="Schermafbeelding 2021-04-02 om 23 13 56" src="https://user-images.githubusercontent.com/633557/113454725-27e70480-9409-11eb-8d9a-a1b931d1af17.png">

Maybe you had something in Username or Password before? When you edit a field, it doesn't hide immediately, but if you select another entry and then return, they will be hidden. If not, it's a bug, let's look into it.

You can actually remove and edit field names, but the usability of it is not great, it should be improved in #1682 in the next release:
- to edit a field: 1. click field value, 2. click field title, 3. enter a new name, 4. press enter
- to remove a field: make its value empty

Field re-ordering is a bit harder to implement because it requires storage redesign, but it's #398. Not sure when we come to it though.

Closing this because it seems to be covered in two issues mentioned above.

**Comment by antelle** [comment]
About the updater: we switched to a new implementation in the latest release, however it seems to be very uncommon (or someone would even call it very bad practice) to replace binary files on Linux, so the updater was disabled in all Linux versions.

**Comment by mkbaranovskyi** [comment]
Yes, you're right: now empty fields hide well now. It also solves my issue with removing unneeded fields.

About the custom field edit: I meant the field name - it cannot be changed after the field is created. I understand that double clicking is taken (for me at least) by auto-type but adding a right-click option to rename it would be nicer than the current need to remove it and re-create. My other issues are solved, thank you.

**Comment by antelle** [comment]
It can, but it’s not very obvious, the way to do it is above: you first need to click the value. Then, if you click field name, it will become editable.

**Comment by mkbaranovskyi** [comment]
Ok, now I see. Thanks for your work and the great app. Sorry for wasting your time, everything works fine, the issue was lame.

**Comment by antelle** [comment]
I hope it will be better in the next release, not the usability is not great as you also noticed.
