### ISSUE TITLE
TOTP secret stored by KeeWeb is not compatible with Keepass2Android

### ISSUE THREAD

**Issue by synchrone** [keeweb/keeweb#1863]
**Describe the bug**
When I set up a TOTP entry using KeeWeb the secret is not readable by Keepass2Android 1.09a-r3. Instead it just shows the stored 32-character secret.

**To Reproduce**
1. Create a new record with TOTP, e.g for Google 2FA
2. Store the 32-character 2FA secret
3. Save the DB
4. Open the DB with Keepass2Android
5. TOTP codes are not generated, instead the user can just see the 32-character secret

**Expected behavior**
I would expect the DB saved by keeweb to be compatible with other kdbx password managers

**Reasons**
Keepass2Android expects TOTP secret value to be formatted like so
```otpauth://totp/Google:<email>?secret=<32-char-secret>&issuer=Google```

I am not sure this is KeeWeb's fault, maybe kdbx standard allows both just the secret AND the URL, and it's KP2A's shortcoming of not being able to read those secrets.

**Comment by FayneAldan** [comment]
This is a bug with Keepass2Android, not with KeeWeb. Please report this on their issue tracker:
https://github.com/PhilippC/keepass2android

This has nothing to do with KDBX. KDBX doesn't even have an official way to store 2FA keys. The issue is KP2A not knowing what to do with just the secret. As a workaround, try adding your future 2FA keys as the full URL. You can Ctrl-V a screenshot of the QR Code into the 2FA setup screen where it says "Scan the QR code". Alternatively, you can scan the QR code from your phone if KP2A has an option to.

**Comment by ikogan** [comment]
Bumping this, if you read the thread in the issue created at Keepass2Android, it looks like KeeWeb is saving the value in an inconsistent way. What's better? Should Keepass2Android be changed to support both `otpauth://` URLs and a raw secret, or should KeeWeb be saving `otpauth://` URLs consistently? I would imagine it's the latter.
