### ISSUE TITLE
Is there any way to import the data in safeincloud?

### ISSUE THREAD

**Issue by NavinChen** [keeweb/keeweb#1983]
There are hundreds of account passwords in safeincloud, I hope to be able to import quickly

**Comment by bdeeming** [comment]
In case it's of any use... A few years ago I wrote a small Python script that converted Safe In Cloud XML exports to CSV, which could then be imported into KeePass (KeeWeb didn't exist back then - not sure what format it expects). You're usage may vary, not sure if they have changed the export format at all since then.
https://gitlab.com/bdeeming/safe-in-cloud-to-csv

**Comment by antelle** [comment]
Hi! It's not supported directly, you need to export it to CSV, as @bdeeming also suggested.

**Comment by NavinChen** [comment]
> In case it's of any use... A few years ago I wrote a small Python script that converted Safe In Cloud XML exports to CSV, which could then be imported into KeePass (KeeWeb didn't exist back then - not sure what format it expects). You're usage may vary, not sure if they have changed the export format at all since then. https://gitlab.com/bdeeming/safe-in-cloud-to-csv

Thank you very much!

**Comment by NavinChen** [comment]
> Hi! It's not supported directly, you need to export it to CSV, as @bdeeming also suggested.

Thank you
