### ISSUE TITLE
Recomended key derivation options

### ISSUE THREAD

**Issue by avently** [keeweb/keeweb#1997]
**Is your feature request related to a problem? Please describe.**
Thank you for this great tool!
For me it is unclear how to choose optimal options for Key Derivation function.

In KDBX 3 we have by default AES with 300000 iterations. In KDBX 4 with Argon2d I have 2 iterations, 1024 KB memory and 2 parallelism by default. 
Is the defaults good enough and recommended in terms of security?

I'm asking because I found [an article on](https://keepass.info/help/base/security.html) on Keepass website that saying this:
```
We recommend the following procedure for determining the Argon2 parameters:

    Set the number of iterations to 2.
    Find out the RAM size of each of your devices on which you want to open your database file. Let M be the minimum of these sizes. Set the memory parameter to min(M/2, 1 GB) (i.e. use the half of M, if it is less than 1 GB, otherwise use 1 GB).
        Example 1: if you have a PC with 32 GB RAM and a mobile phone with 1 GB RAM (on which you want to open your database file), set the memory parameter to 500 MB.
        Example 2: if you have a PC with 32 GB RAM and a PC with 8 GB RAM, set the memory parameter to 1 GB.
    On Windows 10 and higher, the RAM size can be found in the system settings → 'System' → 'About'.
    Find out the number of logical processors of each of your devices. Set the parallelism parameter to the minimum of these numbers. On Windows 10 and higher, the number of logical processors can be found in the Task Manager (right-click onto the taskbar → 'Task Manager') on the 'Performance' tab page.
    Click the 'Test' button.
        If the key transformation takes too much time (longer than you are willing to wait when opening/saving the database file, e.g. more than 1 second), cancel it, decrease the memory parameter and click the 'Test' button again. Repeat this until the required time is acceptable.
        If the key transformation takes too few time (in the case of 1 GB memory), increase the number of iterations and click the 'Test' button again. Repeat this until you like the required time.
    Save the database file and try to open it on each of your other devices. If this takes too long on one of the devices, decrease the number of iterations (recommendation: not less than 2) and/or decrease the memory parameter, and try it again.

```

The value for memory is so different (500 MB or 1 GB vs 1024 KB in KeeWeb).

So how to choose the right options for Key Derivation function? Is the defaults in Keeweb good enough? 

P.s. when I set 512 MB memory, syncing took 5 minutes on a low specs hardware:) (also maybe internet connection was bad in this period of time)

**Additional context**
The latest version of KeeWeb

**Comment by Aetherinox** [comment]
Some time has passed since you submitted this, so I will go based on current standards.
KDBX used AES-KDF / PBKDF2, and at present, the recommended iterations are above 600,000 for SHA-256. That standard was made a few years ago, so I would say that I'd aim more for 800,000+.

In comes Argon2; which is the recommended choice now for security.

Typically for more programs, the default settings are fine (as long as the application is kept up to date).

To give you an example, for my own database, I use `30 rounds, 4096MiB, 6 threads parallelism`, which is quite high. But I also have a 16 core CPU, 32GB memory. However, if I were to take that database and try to open it on a phone, it would either not open, or take ages.  And I also have to take my other devices into account.

So the rule is, take all of your devices into consideration. Take your lowest spec device's memory, and divide by 2.

Start with iterations and parallelism equal to `1`.

Gradually increase your memory setting until the unlock delay becomes just short of unbearable (i.e., as long as you can tolerate), or you run out of memory.

If you have an Android device that has a much slower unlock time than a desktop PC, you can increase the parallelism to make up for this; increase the parallelism until the unlock time is comparable to your PC. If you've maxed out on memory (and parallelism for your mobile devices); you can start increasing the number of iterations.

The unlock time will scale with the number of iterations, so if you increase it from `1` to `4`, your unlock time will quadruple. Thus, increase the iterations gradually (testing after each round).

With my settings I gave above, I usually have about a 7 second delay between database changes. Which may be too slow for some people, but I like my security, and I don't change my databases that much.
