### ISSUE TITLE
Path of Databasefile - feature request

### ISSUE THREAD

**Issue by Harald-Koschinski** [keeweb/keeweb#2118]
KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.7 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36
------------------------------------------------------------------
It would be helpfull to see the full path of the databasefile in the app.

For me it happend again that my different apps on PC and Android worked on different databasefiles  - same name different path.

**Comment by Aetherinox** [comment]
A side note I'll drop here.

Out of box, javascript does not allow for this for security reasons with browsers. The browser should not have local file information, just the file itself.

There are some things you can do to make files more identifiable, and there is a temp path value that can be put in. But if I were to do that, you wouldn't see a path such as `C:\Documents\myvault.kdbx`, you should see the path:

```
blob:http://localhost:8085/1abc6216-17af-caa[...]
```

Which is the local file path relative to KeeWeb since the file is uploaded from your machine, as a blob into local storage for the app itself.

I could consider at the very least; adding the storage type next to certain files, IE
- Local
- Microsoft OneDrive
- Google Drive
- etc

So you have an idea of where the file is stored, or maybe can icon.

**Comment by Aetherinox** [comment]
Alright, I added a new setting to the desktop version

![6NfHujbBEF](https://github.com/keeweb/keeweb/assets/118329232/d0cf1a03-898f-483e-b6ba-2223dced05a3)

If a file is local, it will show the full path. If it's from cloud storage, it will show the name and path, depending on if you have your vault in a cloud subfolder.

![3pF36kYKJf](https://github.com/keeweb/keeweb/assets/118329232/0c0988be-e910-47df-a7ed-02dce1656de3)
