### ISSUE TITLE
KeeWeb

### ISSUE THREAD

**Issue by nilaysingh85** [keeweb/keeweb#2173]
how to use keeweb

**Comment by Aetherinox** [comment]
It depends on what platform you are looking for. Web, or Desktop.
The web version has slightly less features than the Desktop version due to browser restrictions. But if you wish to run KeeWeb via  browser, it is an open.

List of download links are available at
- https://github.com/keeweb/keeweb/wiki
- https://keeweb.info/

Once you download the desktop platform, then just run the .exe / appimage / snap / dmg file (depending on which OS you use).

After KeeWeb is installed and launch, it depends on what you're looking to do. You can either create a new vault to store passwords / credentials, or you can open an existing one that you're migrating over from programs like KeePass.

There's also a web version available at:
- https://app.keeweb.info

**Comment by Aetherinox** [comment]
If you have any other questions, please don't hesitate to reach out to us. I'm cleaning out issues, so I will close this for now.
