### ISSUE TITLE
🐛 Bug: Password generator issues in v1.19.0

### ISSUE THREAD

**Issue by Nmrawe** [keeweb/keeweb#2217]
### Priority

Low

### Version: KeeWeb

v1.19.0

### Environment

Web

### Operating System (Build)

Linux

### Operating System (User)

Windows

### Range of issue

Issue occurs on my own install AND demo site

### Database

Issue occurs with both new + existing databases

### Copy/Paste Environment Details

```shell
KeeWeb v1.19.0 (7d087f79, 2024-12-15)
Environment: web
GUID: 03abb6cf-8cb7-5837-bb77-0b7dc7e706db
UUID: b4926423-fa4d-5304-b4cd-1a23191a1adc
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
```

### Description

1. When using light themes, generated passwords are hard to read due to the black background.
2. The "Spaces" string seems to be hard-coded in English. For instance, in French "Spaces" is translated to "Caractères espacial" but the former is being displayed.

### Steps To Reproduce

1. Choose some light theme.
2. Change the language to French.
3. Open the generator.

### Expected Behavior

Generator's output should be readable when using light themes and "Spaces" should be displayed in its translated versions.

### Attachments

![KeeWeb](https://github.com/user-attachments/assets/43bf467b-7d16-4dd9-aff1-049902bc764a)

**Comment by Aetherinox** [comment]
I'll throw out a fix in a bit. I swear, languages are going to be the death of me.

**Comment by Aetherinox** [comment]
In regards to spaces, I've decided to go the way that keepass did, because it works better.

There will be a new textfield to input a "separator". It will default to the same value, however, any value can be input.

![5Uh6Wa5Nbi](https://github.com/user-attachments/assets/cc257cad-52c9-45f8-aadd-b2b2f7a98f26)

So the setting itself will probably be changed from **spaces** to **separator**. But the language translation itself will be fixed as well.

Some of these languages entries need to be done by someone who knows french, right now I'm running them through 2-3 translators and seeing what the consensus is.

**Comment by Aetherinox** [comment]
The items in this ticket have been completed. Including a new `separator` parameter for passphrases.

**Comment by Nmrawe** [comment]
Thanks!

**Comment by Aetherinox** [comment]
Sure thing. They're not released on the beta site yet, or docker. I'm finishing up an interface request #2221. Once I do that, I'll push the changes and then work on the #1710 stuff.
