### ISSUE TITLE
Question: Is this project alive?

### ISSUE THREAD

**Issue by steveepreston** [keeweb/keeweb#2225]
Hi
I watched this project recently.
while there is recent commits, but last release is for 2021. are you planning to release again in 2024/2025?

**Comment by Aetherinox** [comment]
Project is very much alive. We're not committing to the main branch until the next release is ready. All commits are done to the 1.19 branch

- https://github.com/keeweb/keeweb/tree/develop/1.19.0

While it would seem highly unlikely to not release next year, I always tell people I do not have an ETA on the next release.

The time lapse between 1.18 and 1.19 was large, and in that time, we'd have to update a huge amount of packages, fix bugs, and bring everything up to where it should be. 

And if you want to play with anything new, we update the beta website: https://beta.keeweb.info.

And we roll out docker images now, including a dev branch:

- https://github.com/keeweb/keeweb/pkgs/container/keeweb

Win/Mac/Linux builds are going to be a bit as we finish up the last of the important fixes.
 For stuff like this and other questions, please try to keep to the Discussion forum so that we can keep bugs / feature requests clean.

**Comment by steveepreston** [comment]
Great work. Glad hearing that.

- Does web version send any data/database to server?
- Is web version just for review/edit database? I mean it lacks to be a filler for windows apps/browsers.
- Docker sounds a little creepy for many users, and in case of going to use docker, i think Bitwarden self-host is a competitive option. KeeWeb standalone client will win over that.

Thank you

**Comment by Aetherinox** [comment]
> Does web version send any data/database to server?

No. The entire point of Keeweb is password storage locally without transmission. Unless you are integrating a 3rd party service such as Google Drive, MS One Drive.

> Is web version just for review/edit database? I mean it lacks to be a filler for windows apps/browsers.

The web version and the desktop version are going to differ in regards to some functionality, but overall they both do the same thing. Password management, viewing attachments, creating / viewing new entries, etc. The differences between the two environments are going to be very subtle, such as the way settings are laid out.

> Docker sounds a little creepy for many users, and in case of going to use docker, i think Bitwarden self-host is a competitive option. KeeWeb standalone client will win over that.

It depends on the user. I see quite a chunk of people here have some existing knowledge related to the "self-hosting" community, which means a lot of them are already utilizing Docker as part of their tool-set. This also includes reverse proxies such as Traefik, Nginx, Caddy, etc.

But Docker is just one of our options. We've offered binaries for all major OSes, as well as even a static HTML page which requires no additional installs, It's just a big html file, with javascript and some images. That's practically what the Docker image is, except we've bundled it with Nginx, and also SSL certificate management that way if a user wants to self-host and apply their own SSL certificate, or stick it behind Traefik; they can with little difficulty. 

Personally, I'm an avid user of Docker. Docker and Traefik are insanely powerful tools, and then I couple that with Authentik. I've moved away from bare metal installs, with Traefik and Authentik, I can lock things down as tight as I want, and nobody is getting in unless I miss something.

**Comment by steveepreston** [comment]
Thanks for explanations.

Just to be clear, the title of KeeWeb is "Desktop Application", not a service or server or etc. So in this context most of users typically coming to download an .exe and run it, not to downloading a semi-advanced software and engaging with it to run a "Desktop Application" through it.

**Comment by Aetherinox** [comment]
Cleaning these up so I can see what is left to finish. Any other questions, let us know.

**Comment by steveepreston** [comment]
Thanks. Good luck

**Comment by Neustradamus** [comment]
@steveepreston: Thanks to have done a ticket which follows my initial ticket here:
- https://github.com/keeweb/keeweb/issues/2128

Which follows this locked ticket here:
- https://github.com/keeweb/keeweb/issues/2022

And thanks to @marclaporte who has informed me about this recent ticket.
