### ISSUE TITLE
Mac desktop app: which version am I running?

### ISSUE THREAD

**Issue by matteoipri** [keeweb/keeweb#265]
Hi,
Thanks again for all the great work!
Today I launched the desktop app, went to settings and hit the update button (I set the pref to check for new versions, but don't download them).

The app relaunched, but the app in the Finder seems to be the same: all modification dates of all files are still at 11/07/2016 as when I downloaded 1.2.0.
Clicking on "About Keeweb" in the app menu tells me I'm running "Version 1.2.0 (bdce1c0)".
Going in the settings, it tells me there's non new update available.
Going in the "About" section of the Settings, it tells me "About KeeWeb v1.2.2"
In the "Help" section, it tells
```
KeeWeb v1.2.2 (24cde9a, 2016-07-14)
Environment: electron v1.2.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.2.0 Chrome/51.0.2704.63 Electron/1.2.1 Safari/537.36
```
which shows v1.2.2, v1.2.1 and 1.2.0

How can I be sure I am running the latest version and not some form of mixed version?
What going on here?

Thanks :-)
Matteo

**Comment by antelle** [comment]
Correct app version is in app Settings/About.
Electron version is separate from that, it's the framework on which the app is built. Yeah, this could be confusing because its version in this release is 1.2.x as well :)
Version in "About KeeWeb" menu item cannot be updated by auto-update because we're just downloading html part (about 1MB), without entire app (which is about 40MB), so the version will remain the same as it was downloaded.
