### ISSUE TITLE
Auto-type with special characters not working on Mac

### ISSUE THREAD

**Issue by ericbn** [keeweb/keeweb#279]
Using Mac OS X 10.11.5.

I verified how the code creates an Applescript and spanws the execution of `osascript` with it. From what I checked, I got different results depending on the Input Source enabled on my OS.

This is a test script I created:
```
tell application "System Events"
keystroke "¼"
keystroke "Î"
keystroke "©"
keystroke "~"
keystroke "{"
keystroke "*"
keystroke "!"
keystroke "+"
keystroke "¢"
keystroke "f"
keystroke "4"
end tell
```

This is the result I got by running it having three different Input Sources selected:
* U.S.: `aÎ©~{*!+¢f4`
* Spanish - ISO: `aa©~{*!+¢f4`
* Brazilian - ABNT2: `¼a©~{*!+¢f4`

Expected: `¼Î©~{*!+¢f4`. Actually none of them got it right.  :- (

Plus, we have to consider that the Input Source affects how an accented character is typed. In U.S. we would type `Î` as <kbd>Alt</kbd>+<kbd>i</kbd>, <kbd>I</kbd>. In Spanish - ISO or Brazilian - ABNT2 we would type it as <kbd>^</kbd>, <kbd>I</kbd>. Maybe if we avoid using `keystroke`...

**Comment by ericbn** [comment]
Also, when Spanish - ISO or Brazilian - ABNT2 are enabled, a password like `^A~A´A` gets auto-typed as `ÂÃÁ` (and U.S. actually gave me `^A~AÁ`). You can use http://keepass.info/help/kb/testform.html to check. I'd consider using copy-paste for non-alphanumeric characters as a solution.

**Comment by antelle** [comment]
windows: `^` disappears, other characters are working
linux: some characters are either skipped, or typed incorrectly
So, `^` and other modifiers must be escaped and for non-ascii characters it's better to use copy-paste.

**Comment by antelle** [comment]
Status Update
- **mac** generation has been switched to a native app and it works with different layouts
 - app size is huge, Swift is generating bloated executables, I'll rewrite it in Objective C but now it's working, and that's awesome
- **linux** is now sending `xdotool key U${code}` instead of `type ${text}` and seems to work with different layouts
 - there's a bug with latin1-supplement characters, e.g. `Á` is typed as `â` but this seems to be a bug of xdotool because it cannot type capital character by its name: `xdotool key Aacute` prints `á`. This may be fixed in future, now we'll stick to xdotool on linux
- **windows** not so good here: there's no standard method to simulate unicode user input ([MSDN](https://msdn.microsoft.com/en-us/library/system.windows.forms.sendkeys.send(v=vs.110).aspx) says: _If your application is intended for international use with a variety of keyboards, the use of Send could yield unpredictable results and should be avoided_), some keys cannot be sent even in English locale, needs some hacking

Tested this on string `!@#$%^&*()_+-={}[]:";'<>?,./йух^A~A´AÂÃÁaÎ©~*!+¢f4` in English, Spanish - ISO, Brazilian - ABNT2 and Cyrillic layouts.

**Comment by antelle** [comment]
Current status
- **mac** helper has been re-implemented and now it's 70KB, working with all layouts 🌟 
- **windows** switched to InputSimulator library, working with all layouts 🎉 
- **linux** found more errors in some exotic characters, but we'll leave it as is for this release 😶
