### ISSUE TITLE
Multiple websites for single entry

### ISSUE THREAD

**Issue by hameerabbasi** [keeweb/keeweb#285]
Hello. It'd be great if you could add a way to add multiple websites to a single entry. I could think of a few ways to do this:

1. If the kdbx format supports it, great! Use that.
2. Maybe use some kind of separator?
3. Use multiple fields, named Website, Website2, Website3, etc.

The trade-off between 2 and 3 would be decided by what other apps do/do they support it, for interoperability reasons.

Possible use cases could be:
- Multi-domain websites such as amazon.de and amazon.com, which share the same credentials, and therefore should not be stored separately. Otherwise, updating the overall password once would need two updates in the app.
- More specific passwords for certain subdomains/ports which use different password stores.

**Comment by hameerabbasi** [comment]
Another possible implementation could be regex on the URL.

**Comment by lholznagel** [comment]
When you open an entry you can click on the `more` field and click there `Add new field`.

**Comment by hameerabbasi** [comment]
Yes, I can. But the question is, will auto-type work with it?

**Comment by lholznagel** [comment]
Don´t know. Didn´t know that auto type is in there :D

**Comment by antelle** [comment]
kdbx format supports several titles (by adding target windows), not urls (but at the moment we don't have ui for editing them)
entries will be matched by title and url, if it's available, we can also check additional fields which look like url, e.g. we can test it with a regex.
I'm not sure for now, because matching has not been implemented yet

**Comment by antelle** [comment]
So, we'll search url in all fields. Here's a first sketch of the algorithm, if you're interested: https://github.com/keeweb/keeweb/blob/develop/app/scripts/auto-type/auto-type-filter.js#L43
It will check:
- title, including substrings
- domain name, if both url and entry url are available
- if it's matching, check url path and scheme
- if domain name doesn't match, try to find url in other fields, stop if there's no result

Then it will assign rank to entries and sort them descending, so that entries with full matching url will show first, and so on.
If you have any suggestions, please let me know.

**Comment by asbachb** [comment]
Wouldn't it make sense that the extra fields (or special extra fields) are queried too. When you've some domain account which is used for several services currently you need multiple entries for the same password and you need to update it aswell multiple times. 

Another possibility might be connected entries. So that multiple entries share the same credentials.

**Comment by antelle** [comment]
@asbachb They are queried. However, the URL must be strictly equal to what's there in an extra field.

**Comment by asbachb** [comment]
@tbradsha I know you comment is quite old. But I've exactly the same problem. I wonder if this is an environmental problem. Could you provide some information about your environment.

I'm using Linux & Firefox.

**Comment by tbradsha** [comment]
Since my comment was placed after this was closed, I afterwards created a feature request at #941. As it stands, it's not so much a bug as it is by design. The short answer is that the KeePass spec seems to have a way to handle this, but it's not yet implemented in KeeWeb.
