### ISSUE TITLE
WebDAV with Lighttpd doesn't work

### ISSUE THREAD

**Issue by DigiFlak** [keeweb/keeweb#334]
- what were your actions?
I'm trying to connect to the WebDAV based on Lighttpd server
- what was wrong?
 I have Error: No last-modified header
- app version
1.2.4
- your user-agent (from Settings/Help section)
Web app
- does it happen on Demo or New database?
New

**edit** (@antelle): removed meaningless questions

**Comment by antelle** [comment]
You should enable either this header, or ETag. Otherwise, we'll not be able to detect conflicts.

**Comment by antelle** [comment]
Looks like invalid, if you have some concerns against enabling this header, and believe that we really must support it, please reopen with some details...

**Comment by nagromc** [comment]
Has the same problem. It seems `lighttpd` doesn't send `Last-Modified` header when the extension is `.kdbx`. Just change the extension by `.txt` for instance, and it should do the trick.

Besides, with a `.kdbx` extension, the MIME type (in `Content-Type` header) is `application/octet-stream`. With `.txt`, the MIME type is `text/plain`. So I think the lack of `Last-Modified` header is related to the extension.

If I create two empty files on my webserver:

```shell
touch test.kdbx
touch test.txt
```

I will have the following responses:

```
# Request:
HEAD https://example.com/dav/test.kdbx

# Response:
Accept-Ranges: bytes
Content-Type: application/octet-stream
Date: Thu, 29 Dec 2016 15:51:38 GMT
Server: lighttpd/1.4.35
```



```
# Request:
HEAD https://example.com/dav/test.txt

# Response:
Accept-Ranges: bytes
Content-Type: text/plain
Date: Thu, 29 Dec 2016 15:51:09 GMT
Etag: "2964396523"
Last-Modified: Thu, 29 Dec 2016 15:50:52 GMT
Server: lighttpd/1.4.35
```

It seems that config is written in the [mime.conf file](https://github.com/lighttpd/lighttpd1.4/blob/master/doc/config/conf.d/mime.conf). So you should be able to change that behavior by modifying your `lighttpd` configuration.

**Comment by katomaso** [comment]
Hello, I still don't understand the solution. As far as I understood, the problem is that .kdbx files are not being cached and therefore do not have the Last-Modified header, right?

One solution is to rename my .kdbx file to .txt so it is cached.
Other solution is to modify aforementioned mime.conf in order to set .kdbx to some better content type than octet-stream.

Is this a correct summary of the proposals? I like neither of them though. Why we can't send Last-Modified based on the filesystem properties?

**Comment by nagromc** [comment]
@katomaso It's been a long time since I wrote [this reply](https://github.com/keeweb/keeweb/issues/334#issuecomment-269651093). But I think you got it right. I think the latter one is the best solution since you should change the server configuration since it is related to the HTTP server.

Maybe you should consider using another HTTP server? Personally, I've switched to nginx.

**Comment by stokito** [comment]
@DigiFlak 
Here my working config https://gist.github.com/stokito/0a6274106d407ba6d9fb776e7773445d
