### ISSUE TITLE
Global default for auto-type AND/OR ability to choose which field to (global) auto-type

### ISSUE THREAD

**Issue by peczony** [keeweb/keeweb#356]
It’d be great if the user had the ability to edit the global default for autotype. E.g. I don’t like the default `{USERNAME}{TAB}{PASSWORD}{ENTER}` sequence (especially the `{ENTER}` part), but changing it individually for all entries is a nuisance.

Another way to accomplish what I want is to provide an additional shortcut to (choose and) auto-type only one field at a time (without any `{TAB}`/`{ENTER}` stuff). Like this: I focus in an input field in an app, press something like **⇧^⎇T** and a window pops allowing me to select **a)** which entry to use **b)** which field (username or password or another) from this entry to auto-type.

On a side not, it would be great if one could edit the global hotkeys if one disliked them. (The current ones are fine by me, but flexibility is always good.)

**Comment by antelle** [comment]
> edit the global default for autotype.

You can edit root group and specify the desired shortcut in it, then all entries without custom shortcuts will use it.
> additional shortcut

No, because it's not supported by KeePass format (kdbx) and is also too complex to understand / use. Just copy the field when you need it...
Issue for customizing global shortcuts is here, will be implemented eventually: #348

**Comment by peczony** [comment]
Thanks! It didn’t occur to me to edit root group, maybe you should better articulate if in help section about autotype or something.

**Comment by antelle** [comment]
yes we should add it to docs..
