### ISSUE TITLE
[Feature request] Generator Presets: add "Additional symbols to exclude" option

### ISSUE THREAD

**Issue by Gliptal** [keeweb/keeweb#366]
I've had cases of passwords being invalid for certain websites if some specific charachters are included (e.g. double quotes). I currently check the password and generate a new one if I'm given one with these charachters, but now that we have the generator presets it would be nice to have an exclude charachter option, akin to the include one.

Thanks!

**Comment by antelle** [comment]
Just make a list of characters you want to include, without ones you don't want. We don't want to have possibly conflicting options, it's overcomplicated.

**Comment by Gliptal** [comment]
I understand your position, but I still think a separate option would be nice. Maybe let the user only specify either included or excluded charachter, but not both; although if you implement it someone will end up asking for the possibility of specifying both.

Thanks anyways.

**Comment by antelle** [comment]
Just keep it simple...

**Comment by antelle** [comment]
Now (on beta) it's possible to copy character ranges from generator, so it's even more simple to copy the desired character range, e.g. abcdef...z.

**Comment by snakyjake1** [comment]
I think it is less complicated to have a separate text box to exclude characters.  

![image](https://user-images.githubusercontent.com/8312560/135377043-0a916e36-bcc1-41de-8f78-7b45a62b448d.png)

Why?
Because there are a lot of websites/apps that simply tell you what is not allowed.  For example, FedEx simply states: "Password cannot contain spaces, ~, single quotes, or double quotes." So it would be simple for me to type ~'" and be done (maybe need to exclude "space" too).

Without this feature it makes it less intuitive when I don't see a checkbox for special characters.  There's no checkbox for the special characters, yet special characters are generated in the preview:
![image](https://user-images.githubusercontent.com/8312560/135377359-f5efc97e-7b90-4b89-bf6a-10b5ca593c2b.png)

**Comment by Snake883** [comment]
What I needed to do, which I don't think is simple for the average user, so I'll provide my workaround steps.  This is mainly a problem for passwords in an application/config that cannot handle quotes or other key/non-escaped characters:

1) I didn't find it easy to get to the password generator template, or "Generator Presets", as I was thinking I would find the option in the Settings.
![image](https://github.com/user-attachments/assets/65c4f0a5-6c09-4af8-bee4-8be23bf90aba)

2) Disable all the character options.

3) Add the "additional symbols", minus any symbol(s) you want to exclude:
ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz123456789!@#$%^&*_+-=,./?;:`"~'\(){}[]<>¡¢£¤¥¦§©ª«¬®¯°±¹²´µ¶»¼÷¿ÀÖîüO0oIl

![image](https://github.com/user-attachments/assets/70542df2-c733-4ac5-940d-f2be3b6fa313)

Another workaround is to generate the password as normal, but then manually delete the character(s). But this is not ideal because the next time you generate the password you might get the bad character, not know it until you run into problems.

I do find it a lot simpler to exclude characters.  Why?  The checkbox options are for including symbols/characters.  I don't need another textbox for including additional characters, because I am assuming they are already included in the checkbox options.  What is totally missing is the feature to exclude characters from the checkbox character options.
