### ISSUE TITLE
Add 12 and 24 hour Auto-Lock Options

### ISSUE THREAD

**Issue by Niomar** [keeweb/keeweb#408]
Please update the auto-lock feature to have a 12 and 24 hour option:

keeweb/app/templates/settings/settings-general.hbs,  settings__general-idle-minutes id:

`<option value="720" {{#ifeq idleMinutes 720}}selected{{/ifeq}}>{{res 'setGenLockHour'}}</option>
<option value="1440" {{#ifeq idleMinutes 1440}}selected{{/ifeq}}>{{res 'setGenLockHour'}}</option>`

**Comment by kasoban** [comment]
I'm curious, what's the usecase here? Do you really need to keep it unlocked for 20+ hours, but require it to auto-lock afterwards?

Not to be taken as criticism, I just want to understand what you want to achieve with this. Is it a usability issue? Because, from a security standpoint a database that locks only after several hours of inactivity might as well be unprotected in that regard.

**Comment by Niomar** [comment]
It's a compromise between convenience and security.  If I sit down at my
computer (especially while at work), I'm going to be there for the next 8
hours or so.  I'm not overly concerned with someone getting physical access
to my computer then (since I'm there), so I don't need the database to
auto-lock during that time (nor do I want it to, since typing in a 30
character master password is burdensome).  However, once I stop working for
a few hours (or even a day), I then want to ensure the database does
auto-lock, as it should then be secure since it's likely I'm not at the
computer then.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release
