### ISSUE TITLE
401 Unauthorized with ownCloud WebDav

### ISSUE THREAD

**Issue by n1try** [keeweb/keeweb#443]
When I try to open my .kdbx database in the Keeweb web app using my ownCloud's WebDAV, I'm getting a 401 for the OPTIONS request. There are no `Authorization` headers sent along the request. Chrome says "Failed to load response data."
Doing `curl -XOPTIONS https://myowncloudhost/remote.php/webdav/db.kdbx/` gives me
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
    <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
    <s:message>No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured</s:message>
</d:error>
```

However, the Windows app works fine with the exact same WebDAV URL. I also believe that it worked in the web app just yesterday, but not totally sure (has there been an update?)...

**Comment by antelle** [comment]
Options request must return 200, in order to use webdav from web.
There's no other option.

**Comment by QuibblingAsh42** [comment]
Greetings!  I just installed the app today, and am encountering similar issues.  I've added the suggested config options from the webDAV section of the wiki, but still getting the error in my logs.  I am able to upload and move files around, just not save the KeePass database.  Any other suggestions for moving forward?

**Comment by antelle** [comment]
@QuibblingAsh42 you should troubleshoot your web server, probably it's returning errors on some requests.

**Comment by QuibblingAsh42** [comment]
Well, my apologies...I did some digging, and found I was only seeing 401s for requests coming from the KeePass app on my phone, and not the desktop.  So, knowing my company's proxies do weird things with some requests, I fired up my personal laptop, tethered to my phone, and sure enough everything works perfectly.  I had hoped this might finally be the application that allowed me to have access to my passwords at work, but no such luck.  At least I can read them, so that's 99% of what I needed.  

Thank you for the application, when not behind wacky proxies it works great!!
