### ISSUE TITLE
[Feature request] U2F Support

### ISSUE THREAD

**Issue by Baachi** [keeweb/keeweb#517]
Hey guys!

Is there any plans to support U2F?

I see there is currently an open issue on the electoron page to bring chromiums u2f feature to electron, so it should be "easy" as soons as this issue is resolved, right?
https://github.com/electron/electron/issues/3226

**Comment by antelle** [comment]
It would be tricky, because we'll have to create a plugin for reading this key. Something like this: https://www.yubico.com/why-yubico/for-individuals/password-managers/keepass/

**Comment by danielepolencic** [comment]
Related: Is there any plan to have plugins for keeweb? Or is it the aim to keep it html only?

**Comment by antelle** [comment]
Plugins will be supported in keeweb at some time.

**Comment by nagromc** [comment]
Just to inform the folks who were wondering, the Universal 2nd Factor (U2F) standard is designed to work with USB, **NFC**, or **Bluettoth**. That is, when KeeWeb is compatible with U2F, we will be able to use the web app not only on desktop, but on mobile phone as well just by tapping the physical token on the back on the device.

That said, at the moment, [Chrome for Android doesn't seem to support this feature](https://www.fidesmo.com/nfc-u2f-android/), although Chrome for desktop does since version 38. I guess it is a matter of time.

Firefox for desktop or Android doesn't support U2F yet. But it is [currently under development](https://bugzilla.mozilla.org/show_bug.cgi?id=1065729).

**Comment by antelle** [comment]
We have plugins now.

**Comment by dawidry** [comment]
It would be great to have U2F support.
I don't know how mobile Chrome handle it but generaly it works. If I try to login to github.com it ask me for login/password then it trigger "something" it pop-up over Chrome (see attached screenshot - sorry it's in Polish). Anyway, I touch my NFC U2F key to back of my phone, and it go back to Chrome and I'm looged in.
![screenshot_20170602-124704](https://cloud.githubusercontent.com/assets/13475936/26723124/48fce96c-4793-11e7-901b-37e662d30648.png)

**Comment by sainaen** [comment]
If you're talking about using U2F to “authenticate” on the KeeWeb itself (i.e. for unlocking a db), how would this work without a server?

(a) We'll have to store key handles and public keys somewhere because target db is still locked when we'd need these.
(b) Even if we make a challenge to be always the same (again, by storing it somewhere?), U2F key signs it “concatenated” with several other pieces of data, including a counter, which makes U2F unusable as part of a composite key: every signature is unique.

Note that [the doc](https://www.yubico.com/why-yubico/for-individuals/password-managers/keepass/), linked to in [the second comment](https://github.com/keeweb/keeweb/issues/517#issuecomment-278760378), isn't about U2F but OATH-HOTP, which is a different thing.

**Comment by antelle** [comment]
Well, U2F itself is nou usable, but HOTP keys generated by yubikeys can be used, and they can be read without plugins. However, I tried this in tedt mode for several days, and:
- usability hurts too much, especially with sync
- you need to use backup key too often, which defeats the purpose of a hardware token

**Comment by sainaen** [comment]
> they can be read without plugins

Oh, didn't know that. Could you point to any docs on this?

> usability hurts too much, especially with sync

Yeah, you're right, KeeWeb would have to interact with the key each time it needs to save or reopen db. But I've tried using Yubikey with KeePassXC, and the main pain point for me was the fact that you couldn't open your db on mobile (or KeeWeb/other apps) anymore because there doesn't seem to be any “standard” way to implement this. U2F at least has an official spec.

> you need to use backup key too often, which defeats the purpose of a hardware token

Not sure I understand what do you mean by this.

**Comment by antelle** [comment]
@sainaen in KeePass, you have to press yubikey, and it will insert HOTP into the active field. No additional software is required.
However:
- if you have entered your HOTP and don't want to unlock the db
- sync could be stuck with loss of data, because if you have any local changes, you must unlock the local db first, but HOTP is already moved forward
- pressing something for 3 times waiting for 3 seconds each time, well, might be usable by some true geeks, but is not a good practice

So, it will not be implemented in keeweb itself, but can be added in a plugin (sync support will be very tough to implement).

**Comment by sainaen** [comment]
> you have to press a button on your yubikey, and it will insert HOTP into the active field

D'oh! Totally forgot that HOTP work this way, thought there's some interface to it, like for U2F, that I don't know of. :)

> can be added in a plugin

Sorry for pressing you on this, but I still don't understand where would you store the shared secret and the counter?

**Comment by antelle** [comment]
How it works in KeePass: shared secret is stored inside a database, in some field (encrypted with the db, you can get access to it after you unlock the db).
Master key is computed as Hash(Password) ⊕ (HOTP<sub>0</sub> + … + HOTP<sub>N</sub>).
After you open the db, the counter value becomes N. When you save it again, new master key is Hash(Password) ⊕ (HOTP<sub>N+1</sub> + … + HOTP<sub>N+N</sub>).

**Comment by sainaen** [comment]
Ohhh. I see now. So anything that messes up with the counter on the key breaks this scheme:
* you must save db if you opened it to update the master key with new counter
* you can't use your HOTP for anything else
* there should be only one instance of your db: opening a copy will break the original because the counter has advanced

It *is* really brittle. Unusable, almost.

Thanks for the explanation!

**Comment by sainaen** [comment]
By the way, I've just looked into how OtpKeyProv works. As far as I understand they use the shared secret as a component for the master key, but store it encrypted with several different enc. keys in a companion file. These enc. keys are derived `window` times from (HOTP<sub>i</sub> || ':' || ...  || ':' || HOTP<sub>i+N</sub>) where `i` is in the range from `next known value` to `next known value + window - N`.
It still is brittle, and kind of hacky, but allows counter to advance for no more than `window` ticks from the last seen value, which is nice. But again, you need a companion file.

**Comment by antelle** [comment]
This way it will work better, but the companion file needs to be updated and synced as well, yes. Also, the window should be large enough, however it makes the codes usable N-time, not one-time.

**Comment by sainaen** [comment]
Yeah, well… Good luck to whoever will try to implement this in a usable way! 🙃

**Comment by phoolto** [comment]
Is there any change this will still be added?

**Comment by didlawowo** [comment]
any new about this feature ?  2FA with google auth or 2FA with yubico ?

**Comment by antelle** [comment]
Closing, see #1435, YubiKey support is coming soon

**Comment by michaelblyons** [comment]
U2F does not necessarily equate to YubiKeys specifically. As I understand it, there are all sorts of hardware dongles that do U2F but not HMAC-SHA. This is not a criticism, just a consideration.

**Comment by antelle** [comment]
Indeed, but at the moment I don’t see a way how U2F can be used.
