### ISSUE TITLE
Please add translations requested on OkeSky

### ISSUE THREAD

**Issue by mb-0** [keeweb/keeweb#533]
Hello there,

Looks like there's a bunch of requests on one sky discussions to add new languages (incl mine now); however given some of these are quite old I'm wondering if that's the right (or even this one) forum to request these.

I'll try, worst case: you reject ;-)

List of languages (with ready-to-go contributors requested):
- Hungarian
- Portuguese Brazil
- Vietnamese
- Turkish
- Korean
- Czech
- Romanian
- Chinese (Traditional) - not sure if the one there is the one though ;)
- Ukrainian

Thanks,
mb

**Comment by antelle** [comment]
Hi!
Wow, I haven't seen these requests on onesky and wasn't notified of them, where are they taking place?
Unfortunately, at the moment, we cannot accept more translations, because the app doesn't scale anymore this way, they are already taking 1/4 of the whole app. We'll be able to add these languages, once we have plugin system, which should include translations as well.
Now we support top popular languages of the app, so we'll add these later as well, let's keep the issue open until then.

**Comment by antelle** [comment]
Status update: I implemented pluggable languages support, next version will include it.
By default, KeeWeb will be shipped with these locales:
- de-DE
- fr-FR
- nl-NL

Other locales will be moved to plugins.

**Comment by mb-0** [comment]
Thanks antelle, looking fwd to contrib ;-)

**Comment by antelle** [comment]
Added

**Comment by yarons** [comment]
Can you please add Hebrew and appoint me as a translator? I just couldn't find any official way to do it.

**Comment by antelle** [comment]
Unfortunately Hebrew is RTL, we don’t support it at the moment

**Comment by yarons** [comment]
If it's a matter of crafting the right CSS then I can possibly go for it, anything I can help with?

**Comment by antelle** [comment]
You can try, if it's not many fixes, it will be merged and supported.
We're also using css variables, which should make it easier too.

**Comment by yarons** [comment]
I've posted my work on #831 , if you think it looks good enough we can continue.

BTW You did an amazing job on the CSS, otherwise it would have been a big mess.

**Comment by antelle** [comment]
It needs some icon work, but if everything works apart from that, I'm more interested in the css change

**Comment by yarons** [comment]
OK So first things first, is there a way I can make the changes and test myself? (I'm still not sure what should I change and I don't want to break anything).

I did those changes using the Web app so it's fairly straight forward, in order to make the changes for the other platforms I may need to change and then compile.

I may also need your help with forcing `direction:rtl` on `body` when Hebrew/Arabic/Farsi/Urdu/etc. is selected.

**Comment by antelle** [comment]
You can clone this repo and follow these steps: https://github.com/keeweb/keeweb#building
It should give you a webapp with auto-reload working.

**Comment by yarons** [comment]
This one is fairly simple, I'll try to see if I can implement it with no hassle:

https://medium.com/@elad/the-best-way-to-rtl-your-website-with-sass-105e34a4298a
