### ISSUE TITLE
Firebase Database as a storage

### ISSUE THREAD

**Issue by denis4net** [keeweb/keeweb#535]
Dear development team,
I would like to add free firebase database as a storage for .kdbx files in keeweb. What do you think about these changes: https://github.com/keeweb/keeweb/compare/develop...denis4net:develop?expand=1

There is a brief explanation of some ideas:
https://docs.google.com/document/d/1iHR70vXjdhZ28FrTjr75H_NaR-ZLljZaNdATzqHTUak/edit?usp=sharing

Feel free to comment.  Thanks

**Comment by antelle** [comment]
Too many deps, this won't be merged in master and included in stnadard distribution.
I think, we should develop plugin system in this release, because there's a real need for it now, a lot of requests depend on this.

**Comment by antelle** [comment]
Here's a sketch, how plugin api will look like: https://github.com/keeweb/keeweb/tree/develop/plugins/example. Now it allows to load plugin only once, of course we'll be saving them in release.
Some plugin docs: https://github.com/keeweb/keeweb/wiki/Plugins
I believe, it's safe to close now, because no work will be done in KeeWeb.
