### ISSUE TITLE
local file on self-hosted server

### ISSUE THREAD

**Issue by Thatoo** [keeweb/keeweb#597]
Could it be possible to store files locally on a self-hosted sever?

As I understood, the file of data is stored in the browser. We can save it somewhere (computer, nextcloud, dropbox) in order to open from other browser (other computer).

It would be nice to be able to store it on the server itself, especialy for people who are running Yunohost. It would be nice that users of yunohost could store their files in their own user's folder and whenever they connect to their yunohost account from any browser, their file would be available in the list.
To access keeweb they have to identify themselves to yunohost, keeweb is not publicly accessible.

Here is the issue I open on the keeweb for Yunohost git.

**Comment by antelle** [comment]
Yes, but you need webdav for this.
A small guide which could be useful: https://github.com/keeweb/keeweb/wiki/WebDAV-Config

**Comment by Thatoo** [comment]
My question was exactly how to do without having to tell people to store their file somwhere (on a webdav server)?
Users of Yunohost should just have to login their yunohost (from anywhere, any computer), click on their keeweb tile, enter the password to access inside keeweb. The database file should be stored locally on their yunohost user's folder automatically.
If it's more complicated than that (having to care about a file that they have to store somewhere...) keeweb can't become popular and only geecky people will use it.
Maybe their is something I don't understand but I'm asking why it is not possible to store the file inside the server? I can store download and upload it to/from my computer, why it can't be linked directly with a local folder of the server?

Could you add that option of storage?

**Comment by antelle** [comment]
There's no way.
If you're integrating keeweb somewhere and want to provide storage option, please distribute webdav server with it and pre-define database path.
Well, we should begin with if you're self-hosting keeweb, you're already a geek. So it should not be a problem to setup webdav server. Otherwise, you can just go to app.keeweb.info and select the desired storage, e.g. Dropbox.

**Comment by antelle** [comment]
Another question: what do you mean as 'add that option of storage'? Provide a docker built with nginx webdav module? Or what?

**Comment by Thatoo** [comment]
I might be a geek (I don't know if being able to install yunohost is enough) but my father and mother who are going to use yunohost aren't. If I say webdav to them they'll look at me very weird. 

I don't understand your last question...
I just would like the file to be stored automatically in the yunohost-user's folder, and that the usage become  as easy as : I login to yunohost, I click on th tile of keeweb app, I enter the password to access my keeweb data and I can copy/paste password to login whatever I need to login.
This is happening today but only with oneself's browser. From other computer, you need to open the file (that no normal person would have previously downloaded or stored on whatever else server). Keeweb yunohost should store that file automatically in a folder on the server and open it automatically (with the password) when a user open the app.

Maybe I'm not geek enough and I want something difficult but in my mind, if I can download the file in my computer and then later from an other browser I can upload it, it should not be difficult to add an option to save the file locally on the server and open it locally from the folder (and make it automatic).

Maybe if you don't know yunohost, you should give it a try. It is so far the easiest/friendliest way to self-host a cloud on a rasp at home.  The little geeky of the family (like me) can easily install it and all the family can enjoy it. Yunohost is for me the best way to make decentralised cloud popular. 

By the way, I open the same issue on the github of keeweb for yunohost so if you want to discuss about it with the dev, it's here : https://github.com/YunoHost-Apps/keeweb_ynh/issues/7#issuecomment-293790656

**Comment by antelle** [comment]
You should've described it with more details initially. Now the things are more clear to me.
So, we have an yunohost app, which is integrating keeweb (it's the first time I hear about it). And of course KeeWeb doesn't work as expected, because it knows nothing about yunohost.
Of course, it's an integrated app, it should provide all the necessary resources to save files to the system.
If you're a developer of this app, you should expose a WebDAV endpoint and preconfigure a filename for keeweb, i.e. return all existing files in keeweb config.

**Comment by christopher-davies** [comment]
This is painfull to read....  I still dont think Antelle understands whats being asked for. 

All thats being asked and something I am interested in is and technically nothing to so with yunohost  in purly a technical sense.

Why cant keeweb do a local (php) read_file() of the password database, so the database ip traffic never leaves the server. ie read_file(database.dbk). The database file could for example sit in the same folder as the keeweb index.html, if wanted (ok not secure but).  The idea a webdav server is required for this is shocking. 

There are problems with running a webdav server, ignore all the security issues, corporate files and other security tools block varius HTTP commands and I have seen a very technical PHP based workaround but really it cant be this hard to simply ask the web app to read the file next to it...

Its like doing an include('database.db'); note lack of url because its a local file.

**Comment by vavrecan** [comment]
Hey guys, 
if anybody was wondering how to do this, I did it in my fork 
https://github.com/vavrecan/keeweb/commit/b364f5a86c0d3589db1d64d545328bd020e72038

It allows easy storage on same self hosted server (hiding all other options).
Reading and writing is done through simple php script that should go to /server/ directory. 

User is then asked for password to access server files (which can also be changed in php script) and then he can use keepass with locally stored files. It should be easily to rewrite script to other programming languages as well.

Hope it helps.

**Comment by kasoban** [comment]
@christopher-davies Sorry to say, but I believe you have a bit of a misunderstanding there. There is no such thing as a "local" database file on the server for keeweb, as it is exclusively javascript that is running in the client browser, not "on the server". A local file for keeweb would be a file on the users computer, NOT on the server. Everything (including configuration and database) that it is supposed to know about, has to be transferred to the users browser one way or another. 
And the most secure and reliable way to do that would still be a properly set up WebDAV, just as Antelle explained.

**Comment by OceansCrashing** [comment]
@kasoban "And the most secure and reliable way to do that would still be a properly set up WebDAV" - no.

**Comment by derek-shnosh** [comment]
> Hey guys,
> if anybody was wondering how to do this, I did it in my fork
> https://github.com/vavrecan/keeweb-local-server
> 
> It allows easy storage on same self hosted server (hiding all other options).
> Reading and writing is done through simple php script that should go to /server/ directory.
> 
> User is then asked for password to access server files (which can also be changed in php script) and then he can use keepass with locally stored files. It should be easily to rewrite script to other programming languages as well.
> 
> Hope it helps.

@vavrecan - excellent, thanks!

**Comment by justin-himself** [comment]
> Hey guys,
> if anybody was wondering how to do this, I did it in my fork
> https://github.com/vavrecan/keeweb-local-server
> 
> It allows easy storage on same self hosted server (hiding all other options).
> Reading and writing is done through simple php script that should go to /server/ directory.
> 
> User is then asked for password to access server files (which can also be changed in php script) and then he can use keepass with locally stored files. It should be easily to rewrite script to other programming languages as well.
> 
> Hope it helps.

I want to set up a keeweb server on my family NAS but I don't have a webdav server.
And I don't want to hand my password database to some unknown docker images either.
So a plugin seems to be a perfect solution!
Thanks a lot! You really helped me!
