### ISSUE TITLE
"no last-modified header"

### ISSUE THREAD

**Issue by salmanchan** [keeweb/keeweb#599]
hi,

I open my keepers.kdbx file through webdav, receive the error message
"no last-modified header"

But, there is no problem with other client ( keepass2 or kepass2android )

Version: KeeWeb 1.4.1 fro Mac

How do I solve this problem?

**Comment by antelle** [comment]
Please add this header. We can't work without it.

**Comment by salmanchan** [comment]
I'am sorry. I use a public webdav service, I don't know how to add this header?

**Comment by antelle** [comment]
Then it's not possible to use this webdav server with keeweb.

**Comment by benzkji** [comment]
@antelle I stumbled upon that "no last-modified header" as well, but my server supports it. It was just that I didnt specify a real .kdbx file, but just the / directory... if keeweb could distinguis between files, and then say "no last-modified header" if it doesnt have it, or, directory, and then, say something like "please specify a valid .kdbx file"...this would clear things up, at least for some people...?!

**Comment by antelle** [comment]
Basically we don't know if it's a kdbx file or a directory: kdbx file path can also be something like `http://my-server/my-path/my-file`, without `kdbx` extension. We can require also mime-type, but it will cause the same problems as last-modified. I would say, providing directory name instead of file is not a common problem, so we shouldn't add an extra requirement to solve that.

**Comment by benzkji** [comment]
ok. didnt know about that. yea, just reading the help text above the field could be expected :)
