### ISSUE TITLE
config.json with sensitive webDAV password data accessible from other 

### ISSUE THREAD

**Issue by HalliHalloSchatz** [keeweb/keeweb#603]
- what were your actions?
Configure my self-hosted keeweb with config.json to access my keepass2-db stored in webDAV

- what was wrong?
In the config.json is the webDAV password in clear text and I have no idea to prevent to load the config.json from the browser.
When I have a .htaccess for prevention, keeweb cannot access the file.
When I stored the config.json in a folder, that is not public, keeweb cannot access the file

- app version
newest from branch v1.4.1
- does it happen on Demo or New database?
not interessant
- if you are using a test db without your personal data, please attach it
no
- please, open dev tools in your browser and attach output log from Console tab 
2017-04-18T11:27:45.829Z [app] Loading config from /svn/keeweb/config.json  index.html:16:5316
2017-04-18T11:27:46.584Z [app] Error loading app config Not Found  index.html:16:5799

**Comment by antelle** [comment]
Don't put your WebDAV passwords to config, then they will be stored encrypted. To do this, you have to open a WebDAV file from keeweb UI, not from config.

**Comment by HalliHalloSchatz** [comment]
where is the setting stored? 
I will have only my one webdav keepass database and will use the function showOnlyFilesFromConfig.

**Comment by antelle** [comment]
It's stored in local storage, encrypted with a value, read from kdbx.
> I will have only my one webdav keepass database and will use the function showOnlyFilesFromConfig.

Just to make it clear, once again: if you add a webdav, then webdav password will be in cleartext. There's no possibility to store it securely, because somehow keeweb must read it.
So, it you don't want your password to be stored in cleartext, you should not use this config option and add files manually instead. Then your webdav password will be encrypted.

**Comment by HalliHalloSchatz** [comment]
okay, all clear.

My solution: keeweb with password protected https apache and cleartext in config for my private keeweb.
