### ISSUE TITLE
Disabling and reordering plugins

### ISSUE THREAD

**Issue by EnricoMonese** [keeweb/keeweb#609]
Disabling plugins without uninstalling them and allowing to reorder them

**Comment by antelle** [comment]
+ error handling, + plugin updater - must have for plugin mvp

**Comment by antelle** [comment]
Now we can enable/disable plugins and they are sorted in settings. Plugin reordering is not something useful, we don't need it. Later we'll introduce plugin searching, grouping by function and some other fancy display features.
So, the next step is plugin updater and the most tricky part, gallery (I'm still thinking how to organize it).

**Comment by EnricoMonese** [comment]
I was thinking that reordering cloud be useful for plugins that override or require other plugins to execute before them.

**Comment by antelle** [comment]
That's what we want to avoid. Plugins must never interact. Themes add css only to their namespace. User should never know about technical things like order. If it happens, we'll be enforcing rules and refuse to load plugins which add potentially conflicting rules yo global namespaces.

**Comment by EnricoMonese** [comment]
Fair point. The scenario I was thinking about was for example, let's say there's a plugin that styles only buttons. This plugins' styles should be added in html `head` after styles from themes.
Having plugin styles after theme styles is probably enough, with no need for reordering then.

**Comment by antelle** [comment]
This should be solved with specificity: theme styles are always added with `.th-xxx selector ...`, and themes are always there, even default styles are added with themes. As we're using variables, theme styles always come the first from built-in css, only variable overrides happen in themes, no extra styles are added there (of course, if theme doesn't add anything specific).
Plugins must add something to selectors: either `!important`, or some specificity.
So, the only possible issue is two plugins styling the same element (button, dialog, whatever...), but we can safely assume that it's a conflict and you should not install these plugins together, because probably it will break something else.

**Comment by EnricoMonese** [comment]
Yeah I guess that true 👍
