### ISSUE TITLE
Attached file is trapped

### ISSUE THREAD

**Issue by marco-brandizi** [keeweb/keeweb#622]
I'm trying the last KeeWeb for macOS (1.4.1 df218ae), really nice, thank you.  

I cannot do anything with a .png file attached to an item, except showing it inside the app. No drag/drop to the desktop or file manager, no copy/download option, no "open with..." option.

If this feature is really unavailable, it makes the attachment option and hence the app useless to me (I'm migrating from Universal Password Manager precisely for this feature).

**Comment by marco-brandizi** [comment]
OK, I've tried it more and now I see this can be done by dragging the opened image. Too confusing, I'd like menu options, drag/drop directly on the file icon and to the original name kept when the attachment is dropped back to the file system.

**Comment by antelle** [comment]
Shift-click attachment button to download it:
![xxx](https://cloud.githubusercontent.com/assets/633557/25861215/4f0ad09c-34e4-11e7-8ec6-814367999230.png)

**Comment by marco-brandizi** [comment]
The tooltip doesn't show on my instance, thanks @antelle. Yet, Drag/drop would be a nice additions.

**Comment by antelle** [comment]
It should be visible. Maybe your image is large?
Drag out of an app is something which:
- requires some effort
- will not work on web
- will not be used by most users

We should better consider a download button in image on hover, or increase the discoverability of the tooltip text.

**Comment by Hufschmidt** [comment]
It seems to be that the tooltip is shown behind the data layer.
![unbenannt](https://user-images.githubusercontent.com/11391961/29821340-d35c5b46-8cc7-11e7-910a-9606a1340e5a.png)

Either the tooltip should be rendered in front of the data layer or perhaps even better, placed *below* the attachment buttons?

**Comment by antelle** [comment]
@Hufschmidt it should not happen, how did you manage to do that? Looks like a weird bug.

**Comment by Hufschmidt** [comment]
Nothing special really, this happens with both:
* The Web-App https://app.keeweb.info (1.5.4, Chrome 60)
* The Desktop-Edition (1.5.4, Arch-Linux, from AUR)

## How to reproduce
* Create a new KeeWeb file or open an existing on
* Add new entry or edit an existing one
* Add new attachment to entry  
  Use a file that is *"long"* enough to fill the entire area, eg. an image or text-file with >100 lines
* **???**
* Profit!

**Comment by Hufschmidt** [comment]
I think the issue is with the strong transparency (`opacity`).

### Suggestion 1
Drop `opacity` from _preview-download-text_, add `background-color` to _preview-download-text_, and add some `padding-bottom` to _preview-data_

#### Covering text
![cover](https://user-images.githubusercontent.com/11391961/29861349-47d2e232-8d69-11e7-8257-589dc1bc71c6.png)
This should not be a problem, since the `padding-bottom` ensures that all content will be visible at some point

#### Scrolled to bottom
![bottom](https://user-images.githubusercontent.com/11391961/29861339-3da74aa0-8d69-11e7-8d4e-ae07269a2a46.png)

### Suggestion 2
Remove the tooltip from the scroller, putting the text below it. This way we can ensure that no content will ever be covered by it. :smiley:

**Comment by antelle** [comment]
@Hufschmidt ah, I thought it was some part of desktop visible under the app. Now I see, yes, it should be fixed.
