### ISSUE TITLE
Feature Request: make the file type configurable and could choose a jpg file to append file content

### ISSUE THREAD

**Issue by metasong** [keeweb/keeweb#627]
the default file type is .kdbx, could we make it cofigurable, currently if we do not use any type when store it to cloud, keeweb will add the .kdbx to the file name.

could we append the content to a jpg file? so that if others got the file, and open it it could show the image,  so they will not consider this as a password storage file.
and we can more safely store the file even to github, because the others would just consider this  as a picture.

**Comment by antelle** [comment]
> could we make it cofigurable
We won't do it, but you can always rename your file and open it with keeweb. It will be possible to use such files only from filesystem (desktop app), not from Dropbox, GDrive, etc...
We'll support such files in Dropbox chooser, later, see #179.
> could we append the content to a jpg file?
Appending to a file is not the correct way. I would suggest to think about steganography (embedding kdbx content into other files, mixing their bytes in some sequence), but it's not the task of password manager, you can save to kdbx and use a special app to mix it with jpg or something else. As well as now, you can save to kdbx and just `cat file.kdbx >> file.jpg` and save it to github. Again, we'll not support working such files directly, because the number of cases and the complexity is enormous.
