### ISSUE TITLE
Critical: External request without asking user for it explicitly!

### ISSUE THREAD

**Issue by gloryknight** [keeweb/keeweb#644]
Greetings Developers,
thank for the great soft and your attention to privacy. Here is a bug which effects your promise:

- what were your actions?
Go to plugins while trying to install new languages.

- what was wrong?
The application sends a request to https://plugins.keeweb.info/plugins.json 
without explicitly asking user for the permission.

- app version
v1.5.2 (2017-05-25)

- your user-agent (from Settings/Help section)
Chromium, Chrome. Desctop/Android. WebApp.

- does it happen on Demo or New database?
Allways.

PS: I know that keeweb.info might be considered not external (It is for me).

**Comment by antelle** [comment]
If you go to plugins, what did you expect?

**Comment by gloryknight** [comment]
I expect an explicit warning as it is stated in the documentation!

**Comment by antelle** [comment]
Well, the documentation should say _The app never transmits **your data** unless you ask for it explicitly_. I believe, it's ok to load plugin definitions, if you go to plugins gallery page. Because for example, somebody may ask, why are we loading app manifest at start? In next versions we'll also have to switch to service workers and load it instead, because appcache is getting deprecated. However the fact that we never transmit your data unless you explicitly asked us to store your file on any cloud storage will remain.
Wiki updated, now it's more clear.

**Comment by antelle** [comment]
I've added a button to load plugin gallery, will be included in the upcoming hotfix, to make it even more obvious that we'll load plugins now:
![123](https://cloud.githubusercontent.com/assets/633557/26529812/c1973532-43c7-11e7-8a5b-25cd158789ec.png)
However, again, I don't think it's something critical that we make a request to own plugin gallery, when you go to plugin gallery, and we **will** have service worker soon.

**Comment by gloryknight** [comment]
Great. Thanks. 
I am sure that you transmit no data and have no malicious intent. Therefore, your idea about explicit permissions for any communication is important. This reduces attack surface of the App and increases user trust when it comes to such sensitive data. As to the button: it would be even more obvious if the name of the button was something like: "Load plugin gallery from server".
Good luck.

**Comment by antelle** [comment]
Release uploaded. Thanks for your attention!
