### ISSUE TITLE
Dropbox database issue

### ISSUE THREAD

**Issue by jskrns** [keeweb/keeweb#676]
I used to keep my .kdbx files in Dropbox and about six months ago I switched to using keeweb's Dropbox functionality. I used it for both my work and my personal database. A couple weeks ago, the same password I have always used for one of databases just stopped working! What do I do? I never changed the password and am in a real bind now...any idea what could have happened? 

I can still open the other Dropbox located database just fine. I can open older versions as files. But the most recent version that I saved somehow is not accepting my password. Any ideas?

**Comment by antelle** [comment]
Hello!
It's very strange, because keeweb doesn't change the password itself.
- can you open the same version of db with keepass or other clients?
- is there anything strange vith version history and file size?
- what happens if you re-add it to keeweb?
- is there anything interesting in logs, or just password doesn't match error?

**Comment by antelle** [comment]
Please feel free to reopen with more info, then we'll be able to find the reason.
I understand that somehow it can happen, but on the other hand, I'm using KeeWeb with Dropbox on daily basis and cannot reproduce it.
