### ISSUE TITLE
[Feature request] Sync via WiFi

### ISSUE THREAD

**Issue by shreeshbhat** [keeweb/keeweb#682]
I am not sure if this feature already exists, would love to sync the encrypted file via Wifi.

**Comment by antelle** [comment]
What is sync via WiFi? You can't sync a file without a server.

**Comment by shreeshbhat** [comment]
Functionality like this one.  http://wifimediasync.com/
I feel it would help if we could transfer within the same network, thus, making it more secure.

**Comment by antelle** [comment]
It will require some sort of pairing and open a door for new vulnerabilities, because we'll need to expose something to the network. So, we can't say it's more secure, it's just another type of attack. +we'll need some additional pairing ui here.
I would say, it can be done with a plugin, but it will. e quite hard to use, because installing a plugin on a phone is not that easy, but feel free to create a plugin if you would like to do it.

**Comment by shreeshbhat** [comment]
Thanks for the explanation!
