### ISSUE TITLE
Firefox blocks download of release with "Phishing and Malware Protection"-warning

### ISSUE THREAD

**Issue by phuhl** [keeweb/keeweb#696]
When trying to download the latest release from https://github.com/keeweb/keeweb/releases/tag/v1.5.4 the link for KeeWeb-1.5.4.win.x64.exe and other files was blocked by Mozilla Firefox. A link to this page was provided: https://support.mozilla.org/en-US/kb/how-does-phishing-and-malware-protection-work

**Comment by sainaen** [comment]
It's a global GitHub/S3 issue: the S3 bucket was reported to
> “Try to trick visitors into sharing personal info or downloading software.”
> — [Google's Safe Browsing Diagnostic](https://www.google.com/transparencyreport/safebrowsing/diagnostic/?hl=en-US#url=github-production-release-asset-2e65be.s3.amazonaws.com)

It probably will be resolved shortly, but I don't think KeeWeb's maintainers can do anything while the issue exists.

**Comment by sainaen** [comment]
A-a-and it works now.

**Comment by antelle** [comment]
I guess, this could also happen because the certificate is expired.
However, keeweb is signed with a [timestamp](https://stackoverflow.com/questions/329396/what-happens-when-a-code-signing-certificate-expires), and even the certificate is expired, it should be fine for Windows.
Some other clients, like Firefox, could still check the date and complain about it, which is wrong.

**Comment by antelle** [comment]
Just found the same report for mac.
So, this is the reason: https://www.ghacks.net/2017/07/25/firefox-blocks-all-github-release-downloads-as-deceptive/
