### ISSUE TITLE
Feature Request: Support Markdown Notes

### ISSUE THREAD

**Issue by omidkrad** [keeweb/keeweb#713]
I had originally [requested](https://sourceforge.net/p/keepass/feature-requests/1968/) this for KeePass but the author believed it didn't add any value.

Now KeeWeb seems to be a more proper product to support markdown notes as it is all web-based.

Thanks!

**Comment by antelle** [comment]
Markdown seems to be a better alternative to RTF. And it will also not break the compatibility with KeePass, since Markdown is plaintext as well.

**Comment by omidkrad** [comment]
If there is one feature that would make me switch from KeePass to KeeWeb it is probably this. :)

**Comment by gynet** [comment]
It would be great that keeweb can support notes

**Comment by gynet** [comment]
@antelle Also, I would suggest improving the user experience of text area editing, currently, it's not easy to handle multiple-line text editing.

**Comment by gynet** [comment]
I think Markdown + HTML editors will cover most scenarios for note writing. They are both plaint text format, and there are many WYSIWYG libraries can be used as well.

Since keeweb is a ideal personal secure database, it would be great we can have something similar to https://standardnotes.org/ but without a hosting server. 

@antelle

**Comment by antelle** [comment]
Well, it would be quite hard to achieve the same level of ux as in note editors, because you need to enter password every time and there are some additional fields on entry details. Apart from this, mobile ui in keepass, keeweb, and forks is not the best for note editing. But still, it makes sense to support markdown (and maybe rtf from keepass) in notes.

**Comment by Lukas238** [comment]
Any progress on this? I will love to be able to see my notes rendered.
I'm using markdown now, since I need to format my information any way, regadles the rendering of it.

Thanks!! :)

**Comment by return42** [comment]
FWIW: I do prefer [reStructuredText (reST)](https://en.wikipedia.org/wiki/ReStructuredText#Applications)

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.  

<img width="717" alt="image" src="https://user-images.githubusercontent.com/633557/64913249-c08d3500-d73c-11e9-9eb1-72e689252357.png">

**Comment by Lukas238** [comment]
That is awesome!!

Thanks!! :):)

**Comment by omidkrad** [comment]
Nice! I think this is the feature that pushes KeeWeb ahead of the original KeePass.

Wait... search in KeeWeb is still broken #1022
