### ISSUE TITLE
Feature Request:  Record by record bi-directional sync with another Keepass file

### ISSUE THREAD

**Issue by apastuszak** [keeweb/keeweb#726]
The original Keepass (keepass.info) has a feature that allows the synchronization of two keepass files that is bidirectional and merges changes only.  This allows you to store a "master file" on the cloud service of your choice, and have multiple local copies on various computers that can merge changes, so all the files stay in sync,

http://keepass.info/help/v2/sync.html

It would be very nice if Keepweb could all this feature to the desktop version.

**Comment by antelle** [comment]
This feature is built-in in keeweb. When the file is changed on a remote storage (or you write into a local file), merge happens automatically. There's no need in manual merge.

**Comment by antelle** [comment]
I didn't get your question sorry :)

**Comment by apastuszak** [comment]
So, if my file on say Dropbox has 10 new entries that my local file doesn't have, and my local file has 3 entries that Dropbox doesn't have yet, will 10 entries be pulled down and 3 sent up to Dropbox?

**Comment by antelle** [comment]
It happens not exactly this way physically, but logically yes, what you just said.
So, it will happen this way:
1. you trigger file save, or auto-save kicks in, or you open the file - all of these will start sync
2. try to upload the file
3. if Dropbox version has changes since the last time we downloaded the file - upload it and exit
4. download the latest file version from Dropbox
5. try to open the file, ask user for password if necessary
6. merge the changes
7. go to 2

**Comment by apastuszak** [comment]
You are my hero!
