### ISSUE TITLE
History length setting for no / unlimited history

### ISSUE THREAD

**Issue by kumabon** [keeweb/keeweb#766]
I noticed that in Database settings, History Length setting with a value of 0 could mean something unintended.

Based on my testing, with a value of 0, KeeWeb would save unlimited history items. Most would expect 0 to represent no history item should be saved (i.e. only current version). KeePass would treat 0 as no history too.

DB created by KeePass would put a value of -1 if I uncheck "Limit number of history items per entry" box. While KeeWeb seems to treat -1 as unlimited as well, the interface doesn't like such value and would highlight that box in red.

May I recommend this setting be designed like KeePass - a checkbox together with a value box enabled only if checked. 

Similarly I suspect History size limit would misbehave too.

Thanks!

KeeWeb v1.5.6 (10229e7, 2017-08-31)
Environment: electron v1.6.11
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.6 Chrome/56.0.2924.87 Electron/1.6.11 Safari/537.36

**Comment by antelle** [comment]
Seems to be valid. Let's add a checkbox _Save history_.

**Comment by kumabon** [comment]
Sure either way as long as there are proper ways to represent:
1. Save history with limit (>=1)
2. Save history without limit (-1)
3. No history (0)

Checkbox "Save history"
1. Check box with value >=1
2. Check box with ... another unlimited checkbox? Putting 0 here could work but could be confusing for people jumping between KeeWeb and KeePass. In any case, UI must store -1 in DB.
3. Uncheck box. UI store 0 in DB.

The KeePass way with checkbox "Limit" is not the most elegant I agree, but sort of works...
1. Check box with value >=1
2. Uncheck box
3. Check box with value 0

**Comment by nopivnick** [comment]
I gather this bug is still present, yes?

![screen shot 2018-08-22 at 5 42 42 pm](https://user-images.githubusercontent.com/688639/44492837-e0ceeb00-a633-11e8-983e-079227de5886.png)

as long as I don't alter the value -1 in that field, will my preferred 'unlimited history count' setting remain intact after using KeeWeb to save changes to the database (new entries, entry edits, etc.)?

**Comment by antelle** [comment]
Indeed, it's not fixed yet

**Comment by nopivnick** [comment]
and if I don't touch that value, my history setting will continue to be 'unlimited' despite other changes to the database?

**Comment by antelle** [comment]
No idea, you can check on a test file

**Comment by nopivnick** [comment]
ongoing histories of changes to entries seem to remain just fine after saving, locking, and reopening a `.kdbx` file with KeeWeb if I don't touch the `-1` value in the `Settings » History length` field.

I don't seem to be able to reveal the password when browsing an entry's prior versions, however. is that expected behavior?

not sure if it's relevant but I used a copy of a file that's been modified with both KeePass.exe and KeePassXC over the years. the database is at least 8 years old and I believe it's still `.kdbx` v3.1.

**Comment by nopivnick** [comment]
> I don't seem to be able to reveal the password when browsing an entry's prior versions

perhaps this is related to #973.

**Comment by elyisgreat** [comment]
Also, it seems as though there's an off-by-one error in this counter. if the history length is positive and set to n, it saves n+1 history items. As such, there's no way to disable history and there's no way to save only 1 item of history.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
<img width="607" alt="Screen Shot 2020-03-15 at 15 53 00" src="https://user-images.githubusercontent.com/633557/76703868-429eec00-66d5-11ea-830b-f623e113cb77.png">
