### ISSUE TITLE
There's no option to go back to method "The file is stored in the internal app storage"

### ISSUE THREAD

**Issue by AlexAlabyev** [keeweb/keeweb#800]
**How to reproduce:**

- Go to Settings -> {name of the storage}
- Once you click the button "Save to" and save to file, there will be no option to go back to method "This file is stored in the internal app storage."

**Comment by antelle** [comment]
Hi,
This is done intentionally, to discourage users from saving files to "internal app storage" because it's not that stable as other types. So, if you have saved it to another storage, there's no way back, you're right.
However, if you really want, you can upload the file again and it will be saved to internal app storage.

**Comment by AlexAlabyev** [comment]
@antelle I see. Well, I just accidentally saved it into a file, and want to go back to the previous storing method. What do you mean by _"upload the file again and it will be saved to internal app storage"_
Where do I upload this? Is there a folder in %appdata% for this or something?

And thank you for maintaining this app, it's amazing!

**Comment by antelle** [comment]
Ah you mean the desktop app? You can select it from a file and it will be saved back to it. E.g. put it to My Documents and drag to keeweb.

**Comment by AlexAlabyev** [comment]
@antelle yes, the desktop app. Thanks
