### ISSUE TITLE
webapp pre-defined keydb storage

### ISSUE THREAD

**Issue by port22** [keeweb/keeweb#823]
I am trying to adapt the example config.json but am stuck at

>     "storage": "webdav", // dropbox, webdav, etc...

what exactly is within "etc" ?
I'd like to point to a local file on the filesystem. I tried things like 

`"storage": "keyfile"`

like it is with the desktop app, but had no good guess.

The goal is to pre-define a static file on the webserver's filesystem while the user has no possibility to change to another file or to another storage backend. Best would be to just skip the file-chooser and let the user in without a password (because authentication was done before by webserver)

Any tips how to do this?
thanks!

**Comment by antelle** [comment]
Hi,
> what exactly is within "etc" ?

Google Drive, OneDrive and other cloud storages we could possibly support.
> I'd like to point to a local file on the filesystem

It's not possible: web apps cannot read files from your filesystem.
> The goal is to pre-define a static file on the webserver's filesystem

You can use webdav to load a file from webserver's filesystem. Like this:
```
  "files": [{
    "storage": "webdav",
    "name": "My file",
    "path": "my-file.kdbx"
  }],
```

Technically you can save your file with empty password, however it's not recommended: it leaves the file on the webserver (and clients) completely unprotected, like it would be a plaintext passwords list.

**Comment by port22** [comment]
thanks, that wasn't clear ...  but the file still has to be chosen by the user even if it's the only one available?

> completely unprotected

No, like I said the authentication will be done by the webserver a step before.

**Comment by antelle** [comment]
The file will be pre-selected, but you will have to press enter to open it.
It will be stored in filesystem backups, caches, etc... - I wouldn't leave it without the password.

**Comment by Danis42** [comment]
Hello, what happens if the file is located on the same webserver ?
Is it possible to implement a "local" option to just read the local file of the webserver ?

So the config would look like this
  "files": [{
    "storage": "local",
    "name": "My file",
    "path": "/var/www/keeweb/files/my-file.kdbx"
  }],

this would help to make the Webapp more secure since a webdav config that is usable without knowing the Password only works with predefined "options":{ "user": "webdavuser", "password": "XXX" } and the config.json is readable if you get access to the webpage. So a way to hide the Password in the Config or just get a local access without webdav would be nice.

**Comment by antelle** [comment]
If you have a webdav or just an http server, you can host keeweb on it, and then you can load files without password. We don't have a server software, so loading "local" files would not be possible.
