### ISSUE TITLE
KdbxError: Error FileCorrupt: no meta node

### ISSUE THREAD

**Issue by alexknobbe** [keeweb/keeweb#827]
Goodafternoon.

Some time ago i have imported an kbx file in to keeweb in nextcloud.
This morning i get the following message: KdbxError: Error FileCorrupt: no meta node

How can i resolve this as my kbx file is not located in my files but is loaded in the app?

Thank you

**Comment by antelle** [comment]
Hi!
> my kbx file is not located in my files but is loaded in the app

What do you mean my this? Is the file saved to your filesystem, or it's saved only in browser (i.e. _internal app storage_)?
Is it possible to open this file with other clients, e.g. KeePassX?

**Comment by alexknobbe** [comment]
It is saved only in browser after opening from local desktop.
Keeweb told me after the upload that it will be saved in the internal app storage

**Comment by antelle** [comment]
If so, probably there's no way to recover this file, it seems to be corrupted. Do you have a backup?
You can find this file in AppData directory, depending on your OS, and try to open it.
How did you manage to get this error? I've never seen it before.

**Comment by alexknobbe** [comment]
hmm ok. Where can i find the file when i have used chrome for that?

**Comment by antelle** [comment]
Ah I thought you were using a desktop app because you mentioned “local desktop”. I see now. Well, it's stored inside Chrome's IndexedDB, there's no easy way to download the file.
Probably it's broken, it's better to use a backup of this file now.
Have you done anything special to this file? I'm trying to understand why it could happen. Normally this error doesn't happen, and I don't see a way to repeat it.

**Comment by antelle** [comment]
Please reopen with more info.
I understand that the issue you describe is weird, and it's loss of data which is not cool, but at the moment there's no way to reproduce it, so it's not actionable. I'd be happy to help if you find a way to repeat it.
