### ISSUE TITLE
Shortcuts while app is in background copy wrong site info

### ISSUE THREAD

**Issue by tbradsha** [keeweb/keeweb#943]
Using KeeWeb v1.6.3 (cded8a4, 2017-12-11), Windows desktop.

KeeWeb is in the background. If I go to somedomain.com, and press the keyboard shortcut Shift+alt+C, the password copied is the password for the entry last selected in KeeWeb, not the entry for the current site I am on.

**Comment by antelle** [comment]
Interesting. Could you please provide logs from devtools? This must not happen.

**Comment by tbradsha** [comment]
This seems to be the case (at least for me) on copying the username, password, or URL. There don't appear to be any logs in devtools or app logs for these actions.

**Comment by antelle** [comment]
I don't understand. Is keeweb activated at all? It can't copy a password without logs.

**Comment by tbradsha** [comment]
I agree, it sounds odd. But this is what I've done to troubleshoot, and no logs appear.

1. Enable DevTools.
2. Select my Amazon.com entry in KeeWeb.
3. Minimize KeeWeb to system tray.
4. Go to apple.com in Chrome.
5. Copy some random text to confirm clipboard is not pre-seeded.
6. With Chrome browser focused, press Ctl-Shift-U.
7. Paste clipboard, and this is what shows: "https://www.amazon.com/".
8. DevTools console remains blank.

**Comment by tbradsha** [comment]
As a side note, I even tried with the "beta version" link, but still no text in the console. I'll try on my Mac when I get home.

**Comment by antelle** [comment]
Ah I see, thanks for the detailed steps.  So, copy actions don't select an entry, only auto-type does it.

**Comment by tbradsha** [comment]
Confirmed this is the case on the Mac, too.

**Comment by Coises** [comment]
I’m concerned that there is a plausible use case for the existing behavior which would be broken by changing it as suggested.

Suppose I have an entry for a credit card. I’ve stored the card number in the user name field and the security code in the password field.

Now I want to use it in the checkout form on a shopping site. I call up KeeWeb and find the entry. I make a mental note of the expiration date (which is usually a selection field that can’t be auto-typed). I go back to the site and set the expiration date; then I click in the entry box for the card number and press Shift+Alt+B followed by Ctrl+V; then I click in the security code entry box and press Shift+Alt+C followed by Ctrl+V.

If I have an entry for the shopping site which matches the title on the checkout page, “fixing” this as suggested would break this workflow. Drag-and-drop fields would work if there’s enough room on the screen to overlay KeeWeb (though apparently not on Mac). Otherwise, one would have to bounce back and forth between KeeWeb and the browser.

My suggestion (which I’ll put in a separate feature request soon) is that global hot keys should be configurable. Among the options for each key would be which field to process; whether to select the unique matching entry if one exists (and show the selection dialog otherwise), always show the selection dialog (even if there is exactly one match), or always use the last selected entry; and whether to copy to the clipboard or auto-type.

**Comment by renyhp** [comment]
Is this issue resolved? I can still reproduce this described behavior in Windows on KeeWeb v1.12.1 (149c565e, 2019-10-27).
Also, on Kubuntu 18.04, same KeeWeb version, the same copy shortcuts have absolutely no effect.

**Comment by tbradsha** [comment]
Yes, @Coises has a very valid point, and though I never use it in this manner, I agree. I'd love to have a shortcut that would let me auto-type just the username or password without an intermediate step.

That said, @antelle, what is the shortcut to show the auto-type window? For me it only shows when I do auto-type if there isn't a unique match, which doesn't do me any good for most of the accounts I have.

**Comment by antelle** [comment]
@tbradsha if you disable this option, the auto-type window should always come up:
<img width="694" alt="Screen Shot 2019-10-31 at 07 47 10" src="https://user-images.githubusercontent.com/633557/67919761-bd49ed80-fbb2-11e9-8882-1b9eb682a982.png">

**Comment by renyhp** [comment]
So it seems like #1329 has been brought up again, after a few hours :)

@antelle I get your point, but anyway @Coises's workflow may be accelerated and it would be way nicer if there were a shortcut that forces the autotype window regardless of the setting you mention and of the number of matches.

**Comment by tbradsha** [comment]
Use case scenario for what I want in this issue:

1. I go to a website.
2. The website only asks for a username. I type a shortcut to retrieve the username of this site, and paste it, then submit the form.
3. The next page asks for the password. I again type a shortcut, this time to retrieve the password of the site. I paste it, then submit the form.

Rather than having to pull up KeeWeb, search for the entry, and then use the shortcuts as currently defined, I'd prefer to leverage KeeWeb's ability to filter down and find the correct entry to put in my clipboard all with a shortcut.

**Comment by antelle** [comment]
Let's make it like this:
1. a new shortcut that will always open the auto-type window
2. copy username, website, etc... will remain the same

**Comment by renyhp** [comment]
Is there any news about this new shortcut that will always open the auto-type window? I'm sorry, it is not my intention to rush anybody, I'm just writing this as a genuine question / reminder since this issue is closed.
