### ISSUE TITLE
Is it secure to use the auto fill extension if from localhost ?

### ISSUE THREAD

**Issue by fredhampton** [keeweb/keeweb#952]
I m developing a browser and want to include keeweb as one of the browsers features. 
The users of the browsers would be accessing  keeweb in the browser but from their computer/localhost

Is it secure to use the auto fill extension if from localhost ?
Is there a way to configure keeweb to have the autofill extension activated by default ?

Thanks so much for this great app !!!

**Comment by antelle** [comment]
Hi! I don't quite understand: what do you mean "if from localhost"?
If the keeweb app is loaded from localhost? If you auto-fill passwords from localhost? 

> autofill extension activated by default

No. KeeWeb doesn't know about what's going on in the browser, the only way is to launch it manually.

Also please keep in mind that auto-filling everything using keeweb's fuzzy matching algorithm is probably not that secure and can be exploited.
If you're developing a browser, I would load the kdbx directly there, instead of relying on another app, this can give you more control.
