### ISSUE TITLE
Feature request: Implement an API

### ISSUE THREAD

**Issue by jonbulica99** [keeweb/keeweb#959]
A simple API to read / add / remove password entries would really be appreciated. This is otherwise a really good project. Thanks in advance!

**Comment by antelle** [comment]
Hi! What kind of API do you mean? There are different ways of integration.

**Comment by jonbulica99** [comment]
I was thinking perhaps some kind of a RESTful API. Also, could you elaborate on "there are different ways of integration"? I am trying to find a backend that can access multiple KeePass databases, is lightweight, simplistic and can also be integrated into other applications (e.g. I want to query keeweb for the password of X site, based on properties like URL etc.)

**Comment by antelle** [comment]
We can't implement RESTful API, since it's not a web service, but an app.
> Also, could you elaborate on "there are different ways of integration"?

Now we have an API:
- for browser plugins using keepasshttp protocol
- for browser console, e.g. you can get settings

There can be other levels of integration, like terminal CLI api, exposing some sort of interface, etc...

You can use our core library ([kdbxweb](https://github.com/keeweb/kdbxweb)) to build a restful service, however keep in mind that uploading sensitive information and querying it sounds dangerous.

Restful API, as well as CLI, is outside of our scope. We might think about new plugin protocol implementation or exposing something to browser, but I guess, it's not what you asked for.
