### ISSUE TITLE
Где родноя язык ?

### ISSUE THREAD

**Issue by 74ls00** [keeweb/keeweb#992]
Пользуюсь 1 версией оригинальной программы, потомучто на старых компьютерах не всегда есть нет. Иногда сталкиваюсь с тем что в линуксе этот файл никак не открыть, то есть совместимости нет вообще.
Поиски онлайн варианта привели на сайт, где как я понял файл хранится на сервере и доступ к нему по логину и паролю.
Не вдаваясь в механику, первое что заметил где русский язык.
Ладно сервис новый, создан американцем, начал гуглить и попал на идеальный "перевод" статьи о создании программы на хабре.
Не будем предполагать что автор руский раньше времени.

Скачал программу и мне не понятно почему она так огромна и там ничего нет.
Это движок хрома ?
А где в ней движок проги на яве ?

Ладно открыл перед этим деинсталятор посмотреть что внутри, а там крюкозябры, то есть автор всётаки японец, или руский.
Мне всё ещё не понятно почему автор перевёл прогу на чужие 3 языка, а руского нет.
Она кирилицу то вообще поддерживает ?

----

Ну а теперь главное, как она вообще работает, описаний естественно нет.
То есть в онлайн варианте на сервере хранится мой файл с паролями зашифрованый моим паролем.
Потом он открывается в браузере, где я каждый раз ввожу пароль, им же сохраняются изменения и обратно на сервер идёт как зашифрованый файл.
И этот файл я могу скачать в любое время для оригинального пусть 2 клиента.
Так или у вас чтото своё ?

Офлайн версию использовать смысла нет, 120мб куда нафик.
Я думал реально можно файл в моём браузере открывать

**Comment by Coises** [comment]
![keeweb-ru](https://user-images.githubusercontent.com/37453876/44960623-c4467480-aeb7-11e8-8b27-57fa3a69a562.jpg)

**Comment by antelle** [comment]
@Coises thanks for jumping in! That’s exactly it. The language switcher also shows that other languages are available as plugins, but maybe it’s tricky to find where these plugins are.
I’ll answer in English, since we have more people here in the thread.
Keeweb is written in Electron, that’s why it’s more than 60MB.
Weird encoding in the js is not because we have comments in non-ascii languages: the javascript just contains a lot of other stuff, e.g. WebAssembly code, this makes it unreadable. You attributed it to the language used inside (maybe you meant comments or so), but it has another reason.
The app is translated on OneSky platform, here’s our project: https://keeweb.oneskyapp.com/mobile/sign/in. We have more languages, and it doesn’t scale well, that’s why we have only two popular languages built-in and distribute everything else as plugins. I do speak Russian, but haven’t used it for several years, it’s quite complicated for me to express especially technical things (I use lots of English words and it doesn’t sound like it should). All our translations are crowdsourced, you can also participate if you see anything strange.
About the way it works: it loads kdbx files and works with them right in the browser (js+wasm), you can use other clients as well: keepass, keepassxc, etc.. they should work with keeweb.
I didn’t get what you mean by 120MB and around it, the web version is only 1MB.
